### ISSUE TITLE
ff, fl and fi ligatures

### ISSUE THREAD

**Issue by Paul-Browne** [rubjo/victor-mono#1]
Lovely font. Great job. But those ligatures stand out like a sore thumb.

**Comment by rubjo** [comment]
You think? They were added as an experimental gimmick, to be honest. But I kind of grew fond of them and kept them for now.

However, if the general consensus is that they have sore-thumb-like quality, I’ll remove them. :D

**Comment by rubjo** [comment]
Removed f-ligatures from Roman style, keeping them in the Oblique and Italic variants, at least for the time being.
