### ISSUE TITLE
Is there a way to get the "classic italic" in VS Code instead of cursive?

### ISSUE THREAD

**Issue by jmesy** [rubjo/victor-mono#100]
First off thank you for the font.
Second, this is my `settings.json` file:

```
{
    "workbench.colorTheme": "Default Light+",
    "launch": {

        "configurations": [],
        "compounds": []
    },
    "editor.tokenColorCustomizations": {
        "textMateRules": [{
                "scope": "comment",
                "settings": {
                        "fontStyle": "italic",
                }
        }]
    },
    "editor.fontLigatures": "'ss01'",
    "editor.fontFamily": "'Victor Mono', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
}
```
As `fontStyle` I can have either an empty string, italic, bold, underline or a combination of them.
Is there a way to get "oblique" or the "classic italic" instead of the cursive version?

**Comment by rubjo** [comment]
Thank you for trying the font. The easiest approach I can think of is maybe to not install the Italic style, only the Regular and Oblique? 😉

**Comment by jmesy** [comment]
I am running Linux Mint 19.3 with full hinting and no anti-aliasing: [https://wiki.archlinux.org/index.php/font_configuration](https://wiki.archlinux.org/index.php/font_configuration).
This is how the font looks like on VS Code by placing the font files inside of `/home/user/.fonts/` and running `sudo fc-cache -fv` to install them. Also `"fontStyle": "italic"`.

![Screenshot from 2020-12-20 15-59-59](https://user-images.githubusercontent.com/74905448/102716520-b6150000-42dc-11eb-97ed-b0d89d6ec686.png)

This is what happens if I don't install any of the font files with `Italic` occurring in the filename. Ligatures won't work inside comments. Also `"fontStyle": "italic"`.
![Screenshot from 2020-12-20 15-58-47](https://user-images.githubusercontent.com/74905448/102716521-b6ad9680-42dc-11eb-9741-84afb5d9c4b1.png)

This is the regular installation of the font (without excluding any file) with `"fontStyle": ""`.
![Screenshot from 2020-12-20 15-57-36](https://user-images.githubusercontent.com/74905448/102716522-b7462d00-42dc-11eb-951f-9472e92cfad5.png)

With the regular installation for fonts, both `"fontStyle": "italic"` and `"fontStyle": ""`, ligatures in comments work; comments and code have the same thickness. On the other hand if I don't install the `Italic` fonts, ligatures won't work in italic comments and italic comments will look jagged which I don't like.

But italic looking jagged with full hinting and no anti-aliasing is something which happens with other fonts in VS Code, which I don't know how to fix. Even if it were possible to make ligatures work right now inside of italic comments, there is the problem of jagged, thick italic which is unrelated to Victor Mono.

I find Victor Mono an improvement over DejaVu Sans Mono which comes with Linux Mint as Monospace Regular. In particular without anti-aliasing and full hinting it is thicker than DejaVu Sans Mono. This makes it easier to read and the themes stick better to the fonts. I think now that I will keep testing the font as it is, with either `"fontStyle": "italic"` or  `"fontStyle": ""`.
