### ISSUE TITLE
Font not showing cursives

### ISSUE THREAD

**Issue by friesarecurly** [rubjo/victor-mono#101]
Hey VictorMono,

The cursive font is not showing on my VSC.
I downloaded and installed the ttf files into my Fontbook and changed my font family to "Victor Mono".
Any ideas why this might happen?

![image](https://user-images.githubusercontent.com/61952349/103218278-95eecd80-48e8-11eb-8e0e-0c1f2341f0e1.png)
![image](https://user-images.githubusercontent.com/61952349/103218302-a2732600-48e8-11eb-92cf-f7ece0504e72.png)

**Comment by friesarecurly** [comment]
These are my settings

{
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.rulers": [
        
        ],
    "emmet.includeLanguages": {
        "erb": "html",
        "jsx": "html",
        "jsx": "js",
        "html.erb": "html"
    },
    "editor.tabSize": 2,
    "files.autoSave": "off",
    "files.associations": { "*.erb": "erb" },
    "window.zoomLevel": 0,
    "kite.showWelcomeNotificationOnStartup": false,
    "editor.renderWhitespace": "none",
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.minimap.enabled": true,
    "workbench.colorTheme": "One Monokai",
    "typescript.referencesCodeLens.enabled": true,
    "html.format.indentInnerHtml": true,
    "[json]": {

        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "json.schemas": [
    
    ],
    "html.format.unformatted": "",
    "[html]": {

        "editor.suggest.insertMode": "replace"
    },
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Local Node File",
                "console": "integratedTerminal",
                "program": "${file}"
            },
            {
                "name": "Launch index.html",
                "type": "chrome",
                "request": "launch",
                "file": "${workspaceFolder}/index.html"
            },
        ]
    },
    "debug.javascript.terminalOptions": {
    
    },
    "editor.find.autoFindInSelection": "always",
}

**Comment by rubjo** [comment]
The first thing that comes to mind is this: Are you using a colour theme where some parts are meant to be shown in italics at all? I don't see any italics in the theme One Monokai either.

If you try the built-in theme "Red", you should see italics. (?)

Install a theme where some elements are meant to be in italics, like Ultimate Dark Neo, or override the non-italic theme you prefer and set italic on the elements you want (eg. https://stackoverflow.com/questions/41320848/how-do-i-get-visual-studio-code-to-display-italic-fonts-in-formatted-code/50714195#50714195)
