### ISSUE TITLE
Stylistic choice for single-storey a

### ISSUE THREAD

**Issue by hrjakobsen** [rubjo/victor-mono#103]
Hi, great work on the font! 

The only thing I miss is a single-storey 'a' glyph in the regular style, such as in Monaco ![image](https://user-images.githubusercontent.com/3295293/105042211-e1197d80-5a5b-11eb-812c-6fc7a17b7fca.png) or even the italic version of Victor Mono ![image](https://user-images.githubusercontent.com/3295293/105042549-4c634f80-5a5c-11eb-96d1-2edd2e69e57a.png).

As I assume this is not to everyone's liking it would probably have to be introduced as a stylistic choice like the slashed zero. 

If this is not worth the effort I completely understand, and I'll give it a go myself. However, without macOS and Glyphs, the chance of my hacks resulting in a PR-ready change is slim to none.

**Comment by rubjo** [comment]
Thanks!

Might happen some day, but further work on the font is paused for the time being in favour of paid work.

**Comment by rubjo** [comment]
Added in 1.5.0 as ss01.
