### ISSUE TITLE
ligature for greek letters

### ISSUE THREAD

**Issue by JHenneberg** [rubjo/victor-mono#104]
This is quite useful for programmers from the scientific world. In Julia you can use natively greek letters but in other programming languages you can not. 

`Sigma` -> `Σ`
`sigma` -> `σ`

```fortran
σ_eqv = sqrt(σ_xx**2 + σ_yy**2 - σ_xx * σ_yy + 3 * σ_xy**2)
```

Beautiful isn't it?

**Comment by rubjo** [comment]
Yes, probably beautiful, I wouldn't really know. :)

Don't have any plans to introduce more ligatures now, though, and don't see how in your example one could be made to make the code look more clear / refined / nice.
