### ISSUE TITLE
Enable cursive fonts in certain reserved keywords in neovim

### ISSUE THREAD

**Issue by dhavalsavalia** [rubjo/victor-mono#106]
Hello everyone,

I recently installed Victor Mono fonts in neovim and they look fabulous! However, it is only enabled for the comments using `highlight` command in `init.vim` file. I was wondering if there is any way to enable cursive fonts for reserved keywords as displayed at [https://rubjo.github.io/victor-mono/](https://rubjo.github.io/victor-mono/)

![Screenshot 2021-02-07 at 9 12 09 PM](https://user-images.githubusercontent.com/27001046/107151542-252bde00-6989-11eb-947b-6fc75ab712f7.png)

The above is what my current setup looks like. 

Any help is appreciated.

Thank you!

**Comment by alexeyten** [comment]
That’s configured in your vim’s colorscheme.

**Comment by dhavalsavalia** [comment]
Hi @alexeyten,

Thank you for your prompt response. As you suggested, I added options to italicize in my [`gruvbox`](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_italic) colorscheme as show below,

![Screenshot 2021-02-07 at 9 54 57 PM](https://user-images.githubusercontent.com/27001046/107152668-219b5580-698f-11eb-9212-f7361666bd89.png)

However, it did not seem to have an effect on reserved keywords in demo code from the website.

**Comment by rubjo** [comment]
@dhavalsavalia Glad to hear you were able to make it work.

> You can do `:exe 'hi '.synIDattr(synstack(line('.'), col('.'))[-1], 'name')` to see what highlight group the item under cursor belongs to.

This made me laugh a bit. 😄
