### ISSUE TITLE
Bold fontStyle in vscode broken?

### ISSUE THREAD

**Issue by kbd** [rubjo/victor-mono#107]
I have `editor.fontFamily` set to "Victor Mono Medium".

Setting docstring text to bold as follows:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [...],
                "settings": {"fontStyle": "bold"}
            },
```

actually makes the text *less* visible, and more washed out. Here's a normal, then "bold" screenshot:

![Screen Shot 2021-02-07 at 5 33 34 PM](https://user-images.githubusercontent.com/728060/107164125-d0796a80-696a-11eb-8346-f7556f818828.png)

![Screen Shot 2021-02-07 at 5 34 12 PM](https://user-images.githubusercontent.com/728060/107164128-d40cf180-696a-11eb-95a9-020694445914.png)

**Comment by rubjo** [comment]
Hi, and thanks for trying the font.

Try using "Victor Mono" as font family, like this:

https://user-images.githubusercontent.com/42270947/107195748-09a8ed80-69f2-11eb-8f16-9c18837d83b4.mov

**Comment by kbd** [comment]
That worked, thanks so much. And, thanks for Victor Mono, it's awesome.
