### ISSUE TITLE
Not able to get ligatures in termial

### ISSUE THREAD

**Issue by aphive** [rubjo/victor-mono#108]
First off, thanks for making this beautiful font, I have been searching all over for a nice looking terminal font that looks futuristic and easy to read, this is fulfilling all my needs so far, except for ligatures but I'm pretty sure it's something I'm missing.

I work on both Mac and Ubuntu and can't seem to get this to use the ligatures for powerlevel10k on either iTerm2, Mac Terminal or Gnome Terminal. I can get ligatures to show if I use a different font that supports it.   In iTerm2 I had to resort to using Victor as my main font and then set a different font for the ligatures.

Is there something that needs to be done when downloading the font or when calling it?

### With Victor in Ubuntu Gnome Terminal
![Victor_no_ligatures](https://user-images.githubusercontent.com/6079962/111716614-6767fb00-8824-11eb-9bc3-e6bd7e4fdaae.png)

### With Meslo Ubuntu Gnome Terminal
![Meslo_ligatures](https://user-images.githubusercontent.com/6079962/111716687-8ebec800-8824-11eb-9042-586219cb70bc.png)

## Thanks
Also just want to say, this font looks amaaazing, even in vim.
![Victor_in_vim](https://user-images.githubusercontent.com/6079962/111716966-186e9580-8825-11eb-8861-c81db7847f34.png)

**Comment by alexeyten** [comment]
What do you mean by powerlevel10k ligatures?
AFAIK there’s no ligatures but a tons of custom glyphs in private area that are exist in MesloLGS NF font (where NF stands for NerdFont patch, I guess), but don’t exist in Victor Mono.

**Comment by rubjo** [comment]
Yeah @aphive, what you probably want is the Nerd Fonts version of Victor Mono which has added icons: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/VictorMono

Thanks for trying and liking Victor Mono!

**Comment by aphive** [comment]
Sorry to reopen but is that what you are using as well as the author of the font? You show a screenshot of p10k showing all the icons and such as in my screenshot using Meslo.   Just making sure I'm not missing something.   I'll try the Nerd version.
