### ISSUE TITLE
char 'e' is different between all styles, with font size 12 or 14

### ISSUE THREAD

**Issue by rd-su** [rubjo/victor-mono#109]
Hi,

First of all, thanks for this great font!

Before I was using [Input](https://input.djr.com), but found this one better...

I'm using it with Notepad++, and the char 'e' is different between all styles, with font size 12 or 14.

example with Regular 12:
![2021-03-29_21h08_13](https://user-images.githubusercontent.com/10651797/112894072-51cfbc80-90d3-11eb-8a77-0465a956adcb.png)

example with Medium 12:
![2021-03-29_21h09_09](https://user-images.githubusercontent.com/10651797/112894079-55634380-90d3-11eb-85ff-572528a0814e.png)

Regards

**Comment by rubjo** [comment]
Hi, and thanks for trying the font. :)

This is a font hinting issue which is not much to do about, other than increasing the font size, getting a higher-resolution display and/or using something else than Windows.
