### ISSUE TITLE
Why is the 'Bold' variation is italic?

### ISSUE THREAD

**Issue by ijasxyz** [rubjo/victor-mono#11]

**Comment by rubjo** [comment]
Hm. Good question :)

Can you tell me a little more about your setup, how you installed the fonts, what apps you see the italic version in? Screenshots?

**Comment by ijasxyz** [comment]
I have the following setup.

PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-50-generic

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

I have copied the ".ttf" fonts into the `.fonts` folder. 

Please check the screenshot.

![Screenshot from 2019-06-26 11-56-39](https://user-images.githubusercontent.com/535233/60156419-25a25000-980a-11e9-8372-cb21e851db95.png)

**Comment by rubjo** [comment]
And is this something you see in other software as well? A quick web search reveals multiple posts here and there about font rendering issues in JetBrains apps.

**Comment by ijasxyz** [comment]
Yes. I tried with sublime text as well. It's the same.

![Screenshot from 2019-06-26 14-29-53](https://user-images.githubusercontent.com/535233/60166487-e9c5b580-981e-11e9-9d59-074a39b2863a.png)

**Comment by ijasxyz** [comment]
But not in the default text editor `gedit`.
![Screenshot from 2019-06-26 14-31-31](https://user-images.githubusercontent.com/535233/60166631-272a4300-981f-11e9-927d-a4f3516c6009.png)

**Comment by rubjo** [comment]
Reproduced on Ubuntu 18.04 (and, for fun, on 19.04 and latest Arch as well).

Not sure what to do about it, though. It’s weird that it opens fine in Gnome Fonts / Font Manager / FontForge / Terminal when set as the default monospaced font.

I can try to post a question on the forums for the font software I use.

**Comment by rubjo** [comment]
Could you try to redownload and install the updated version from the web site now? Looks OK at least in Sublime on 19.04 for me.

**Comment by ijasxyz** [comment]
Thanks. I re-installed the fonts, but it's the same.

**Comment by rubjo** [comment]
Font cache issues, maybe?

Screenshot: 19.04 with latest version. PHPStorm's Color Scheme Font setting here is Victor Mono Medium at 16px.

![Skjermbilde 2019-07-01 kl  10 00 55](https://user-images.githubusercontent.com/42270947/60420293-ad5fd400-9be7-11e9-84a3-de8c601e277a.png)
