### ISSUE TITLE
Contact form / VSCode theme

### ISSUE THREAD

**Issue by hiringManager** [rubjo/victor-mono#111]
Hi, could you perhaps add a contact form of some kind to the main website? I've also recently discovered your semi-obscure vscode theme, and was wondering if there may be any future updates to it.

Thanks!

**Comment by rubjo** [comment]
Thanks for the suggestion, but I don't really feel the need. Open a GitHub issue like you have if you have questions, or scroll down to the bottom of https://rubjo.github.io/victor-mono/ to find an email address.

I should probably link to the VS Code / Sublime Text themes on the website for anyone interested.

:)
