### ISSUE TITLE
The Slashed-Zero stylistic is having a different height than other glyphs

### ISSUE THREAD

**Issue by voltagex007** [rubjo/victor-mono#112]
I saw the Issue of slashed zero and I too wanted it. This is not a call for a immediate that will make my work finish instead its just a reminder that the glyph height is different.

I use ST4 (4107) with Victor mono as the font (font size: 12). When I use the stylistic set '01' the slashed zero height is a bit higher than all other glyph. This is not making me feel bad instead I want to tell you this and hope for a response for that. This might be a start of my contribution to this font.

**Comment by rubjo** [comment]
Hi, thanks for reporting. I'm not seeing this with any font size on any resolution, high-DPI or low-DPI display. Can you provide a screenshot / video of switching ss01 on and off?

**Comment by voltagex007** [comment]
Sure, here's the 'settings' in Sublime Text 4. Notice the 0 being higher than other glyph (compare with 1, its higher than other capital Letters from English too).

![ss01 in Victor mono](https://user-images.githubusercontent.com/82705072/119606287-efafe100-be0f-11eb-815a-2a7996006cbd.png)

**Comment by rubjo** [comment]
Strange, I don't know why this happens. What OS / screen resolution is this?

**Comment by voltagex007** [comment]
> Strange, I don't know why this happens. What OS / screen resolution is this?

Screen Res : 1366 x 768
OS : Linux Mint 21.1 (Ulyssa)
GTK Theme : Any GTK theme does this (Adapta, Whitesur)
DE : XFCE4
Device : Laputop

Never changed DPI, Screen Size is the same as Resolution.

BTW I might try reinstalling the great font.

**Comment by rubjo** [comment]
Did you manage to fix this? Could you perhaps test with a different OS or screen resolution?

**Comment by kenmcd** [comment]
This could be an issue with the font config hinting settings in Linux which can override the font hinting, 
and/or the version of FreeType included (which can have issues in older versions.
Because the font size 12 hinting looks fine (even good).
![slashed-zero-hinting](https://user-images.githubusercontent.com/844920/125859120-dd9fb534-a7f5-4529-ae34-7e4326ad4943.png)

**Comment by voltagex007** [comment]
I currently dont have a different OS (sorry about it) But all I did was use the Nerd Font (which I require for my terminal). Also I'm not a good person with font knowledge.

Thanks for the response and a wonderful Font

-V

**Comment by rubjo** [comment]
Ok, closing this: fix is probably looking more into Linux font hinting / Freetype / experimenting with the desktop environment settings.
