### ISSUE TITLE
IDEA how to use?

### ISSUE THREAD

**Issue by luzihao1234** [rubjo/victor-mono#113]
IDEA how to use?

**Comment by rubjo** [comment]
https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html

**Comment by sebisteiner** [comment]
@rubjo The "semi-connected" italics were not working for me in IDEA products. I had to apply this workaround and delete all oblique styles: https://youtrack.jetbrains.com/issue/JBR-1776#focus=Comments-27-4491852.0-0
