### ISSUE TITLE
Unicode Range

### ISSUE THREAD

**Issue by DecliningLotus** [rubjo/victor-mono#114]
We've been supporting Victor Mono at [Fontsource](https://github.com/fontsource/fontsource) for a while and I've been wondering if you could provide the values for the CSS unicode-range selector? That would be super useful for the project and users downstream.

Thanks!

**Comment by rubjo** [comment]
I guess I could (although I don’t really  understand from your docs how you or your users use unicode-range within Fontsource). 🙂

To be clear, what you’re asking for is a complete list of unicodes for all glyphs present in the font file? I’m sure there must be some tool to generate something like that…

**Comment by DecliningLotus** [comment]
An example could be something like [this](https://github.com/fontsource/fontsource/blob/main/packages/roboto/400.css).

In your case, I'd assume the range of characters supported are only in the Latin subset? Whilst not maybe useful by itself as a single subset, unicode-range could come super useful in some edge case multi-font stacks or if you support multiple subsets of languages. It's also data I'd love to add into an API that developers could possibly use into making more tools.

I haven't found any actual tools for finding the characters from woff format 😅 I've seen it in build steps when compiling the source glyphs, but that's way out of my skill set, sorry.

Totally understand if it's a big ask.

**Comment by rubjo** [comment]
Victor Mono has, simply put, Latin, Cyrillic and Greek glyphs. I’m no expert here, but from the example with Roboto, it looks like unicode range here doesn’t really have to do with the font per se, but rather the character set being asked for. Latin has its range, Latin Extended has its range, Cyrillic another and so on. Which would be the very same ranges for *any* font, no?

That said, Victor Mono doesn’t cover everything in all character sets, so if one for some reason only wanted to list the covered glyphs for each character set, that’s probably possible. Although I’m still wondering about a real-world usefulness of this (any examples in the Fontsource docs?). I’ll have a look some time to see how easy it is to export something like that out from the Glyphs app.

**Comment by DecliningLotus** [comment]
The ranges aren't necessarily the same for any font, but rather what the font supports.

Having multiple subsets is where unicode-range shines in real world scenarios, especially as a webfont. For example, your font is split up into 3 separate files - Latin, Cyrillic and Greek. Each with its own unicode-range as shown in the Roboto example above. The browser reads the body of the webpage and if there are no Cyrillic or Greek characters used that match the specified unicode-range, a fetch request will not be made for those specific font files. 

Compared to downloading one large file with support for all characters that many might not use, splitting it up and only downloading what's needed would lead to a reduction in webpage payloads. Especially when a majority of websites only need the Latin subset only.

It's even more useful for extremely large languages like [Japanese](https://github.com/fontsource/fontsource/blob/main/packages/noto-sans-jp/400.css) where they split it up even more.

**Comment by rubjo** [comment]
Yes, I get the principle behind unicode-range and not downloading font files until a character is used.

> The ranges aren't necessarily the same for any font, but rather what the font supports

Hm. I’m still looking forward to a code example on Fontsource, maybe with a couple of the fonts you have with ranges already defined. 🙂

**Comment by DecliningLotus** [comment]
I don't understand what code examples are you looking for. The change is reflected in the CSS files, which won't change how consumers import the package. I don't see why extra documentation is needed.

`import @fontsource/roboto` already comes with unicode-range included since Google provides those values. `import @fontsource/victor-mono` does not since we don't have the values. They're both just importing CSS files.

**Comment by rubjo** [comment]
Sorry, didn't mean to be slow, but I might have misunderstood this from the outset. So when splitting up Victor Mono, for the Cyrillic files, instead of just defining the range to be the complete basic range 0400-04FF, you only want to include those actually present in the font? So that if a page contains *only* the more obscure Cyrillic characters in the basic set, the font download is not triggered?

Here's a unicode list for Victor Mono, if that's a start. :)

[victor-mono-unicodes.txt](https://github.com/rubjo/victor-mono/files/6800716/victor-mono-unicodes.txt)

**Comment by DecliningLotus** [comment]
That's good enough, thanks! I'll look into integrating that in a week or so hopefully!
