### ISSUE TITLE
Question | How can I use the cursive font in comments ?

### ISSUE THREAD

**Issue by me-nkr** [rubjo/victor-mono#115]

**Comment by rubjo** [comment]
Hi there, thanks for trying the font. 🙂 What code editor do you use?

**Comment by me-nkr** [comment]
VS Code

**Comment by rubjo** [comment]
You have to use a theme that has rules for italicising certain parts of the code (like eg. comments). Try installing this one:

https://marketplace.visualstudio.com/items?itemName=rubjo.ultimate-dark-neo

**Comment by me-nkr** [comment]
I was able to italicize comments using textMate rules under tokenColors. The problem is that it's not cursive

**Comment by rubjo** [comment]
So it’s oblique, not cursive? Can you verify that you have the italic styles of the font installed (ie. do they show up in any other app?)

**Comment by me-nkr** [comment]
I'm using victor mono medium

**Comment by me-nkr** [comment]
Earlier I was using `'Victor Mono, Medium'`, which didn't work but using `'Victor Mono'` worked. But the font is too thin for me, and I want a bit bolder font.

**Comment by rubjo** [comment]
What operating system do you use? And again, does italic work in other apps for all weights?

If not, there are probably font files you haven’t installed (like the Medium Italic one you mention doesn’t work).

**Comment by me-nkr** [comment]
I'm using ubuntu 20.04 and I was able to get cursive comments

I have installed regular, medium and medium italic

**Comment by rubjo** [comment]
Can you list the Victor Mono font files in your  ~/.fonts folder (or /usr/local/share/fonts, if that’s where you put them)?

Again, in a different app, like a word processor, can you select Victor Mono Medium and get true italics?

**Comment by me-nkr** [comment]
> Can you list the Victor Mono font files in your ~/.fonts folder (or /usr/local/share/fonts, if that’s where you put them)?
 NO
> Again, in a different app, like a word processor, can you select Victor Mono Medium and get true italics?
Yes

I was able to get the cursive text in vscode too

**Comment by rubjo** [comment]
Ehm, are you saying that the problem is solved? 🙂

**Comment by me-nkr** [comment]
is it as simple as installing the bold font or is there any tweaking to be done in vscode ?

**Comment by rubjo** [comment]
Install the weight(s) you want, then set the desired font weight in VS Code.

**Comment by alabotski** [comment]
@rubjo Hi How disable cursive in comments?
As for me it's very ugly

<img width="787" height="389" alt="Image" src="https://github.com/user-attachments/assets/75e38bbe-cc3c-4a7f-bd9c-35e5a3a549e4" />

**Comment by rubjo** [comment]
@alabotski There are a few ways of doing it, depending on what editor you use:
- Simply don't install the italic font files
- Pick an editor theme that doesn't use italic for comments etc.
- Add an editor setting override which disables italics everywhere
