### ISSUE TITLE
Unable to get cursive work on Kitty

### ISSUE THREAD

**Issue by mushi-nova** [rubjo/victor-mono#117]
I really love the font and I been trying it out. But somehow I'm unable to get the cursive ligatures to work. Here's a picture of my Rust code

![2021-08-08-004040_665x725_scrot](https://user-images.githubusercontent.com/62972573/128611438-ef0c8570-f8de-46a1-8b4d-63841b5dad47.png)

Currently, I have set my font by the following but it is not working.

```
font_family        VictorMono Nerd Font Mono                          
bold_font           auto                                               
italic_font           auto                                               
bold_italic_font  auto
```

I have also set the `font_features VictorMono-Medium +ss01`. But still there hasn't been any change regarding the cursives. Am I missing anything? Any sort of help is totally appreciable

**Comment by rubjo** [comment]
Hi! Thanks for trying the font.

Could it be this simple: The syntax colouring theme in this screenshot isn’t using italic for any part of the code?

**Comment by mushi-nova** [comment]
Thanks it was a really apt answer. For anyone looking for the answer I did

For Neovim
`vim.cmd('au ColorScheme * hi Comment cterm=italic gui=italic')`

For Vim
`hi Comment cterm=italic gui=italic`
