### ISSUE TITLE
Unable to get it working on Alacritty 

### ISSUE THREAD

**Issue by Decapitater** [rubjo/victor-mono#121]
hi ,
i am unable to get it working on alacritty 
 
Error = [ERROR] [alacritty_config_derive] Config error: font: invalid type: unit value, expected a mapping

family: VictorMono
@rubjo

**Comment by rubjo** [comment]
I've never used Alacritty, but could this be a corrupt config / typo? Maybe posting an issue in the Alacritty repo will get you some more answers.

**Comment by rubjo** [comment]
Quickly testing it now, I managed to get the same error as you when only the "font:" and "normal:" line was uncommented. Did you remember to uncomment the "family:" line in the config?

<img width="634" alt="Skjermbilde 2021-11-09 kl  08 17 29" src="https://user-images.githubusercontent.com/42270947/140879075-4f38a54c-dcbf-4a5b-a4e5-4d32ba796c88.png">

**Comment by Decapitater** [comment]
I am using exactly the same , however i use starship + alacritty themes npm package
Also the numbering is different 
As mine is later around 147

**Comment by Decapitater** [comment]
Holy guacamole , my font and '# Normal' line was misaligned 
Thanks 

Btw i love the theme any names

**Comment by rubjo** [comment]
+1 for "Holy guacamole" :)

Theme is my Ultimate Dark Neo for Sublime (https://packagecontrol.io/packages/Ultimate%20Dark%20Neo), also exists for VS Code (https://marketplace.visualstudio.com/items?itemName=rubjo.ultimate-dark-neo) but alas not for Alacritty.
