### ISSUE TITLE
New font style for seven

### ISSUE THREAD

**Issue by gleich** [rubjo/victor-mono#122]
When I write sevens on paper I like to put a dash through it horizontally. If it isn't too much trouble it would be awesome to have victor mono expose a font feature to enable this option. Lemme know if you need any clarification on this!

**Comment by rubjo** [comment]
Good idea, I write my sevens like that myself, actually. Will be included in the next release.

**Comment by rubjo** [comment]
In latest version, this is stylistic set 6.

**Comment by gleich** [comment]
Amazing, thank you!
