### ISSUE TITLE
ligature joint request (like ---- or ====  when >=4)

### ISSUE THREAD

**Issue by NextAlone** [rubjo/victor-mono#123]
like this in Fira Code
![image](https://user-images.githubusercontent.com/12210746/142727258-8ce4630f-361e-4c0c-9562-979974aedacb.png)

**Comment by rubjo** [comment]
Thanks for the suggestion, but I'm not going to implement that. AFAIK it's impossible to do without glitches (https://github.com/tonsky/FiraCode/issues/1081), so it's not worth it.

**Comment by NextAlone** [comment]
Got that, thanks for your work
