### ISSUE TITLE
Ligature request: cokleisi composition operators

### ISSUE THREAD

**Issue by skykanin** [rubjo/victor-mono#126]
Since Victor Mono includes ligatures for `>=>` and `<=<` which are the commonly used
operators for kleisli composition in [Haskell](https://www.haskell.org) it would be nice if it also included ligatures for the
commonly used *cokleisi* composition operators `=>=` and `=<=` as they look quite ugly at the
moment because they're partially captured by the `=>` and `=<` ligatures.

![image](https://user-images.githubusercontent.com/3789764/148676854-12ef54b0-4b7d-468f-b179-515309866606.png)

**Comment by rubjo** [comment]
You got it! Give me a couple of days.

**Comment by rubjo** [comment]
In v1.5.2.
