### ISSUE TITLE
Homebrew Missing VictorMono-ItalicBold.otf

### ISSUE THREAD

**Issue by esparkman** [rubjo/victor-mono#13]
➜ brew cask install homebrew/cask-fonts/font-victor-mono                                                     11:42:46 PM
==> Satisfying dependencies
==> Downloading https://rubjo.github.io/victor-mono/VictorMonoAll.zip
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'font-victor-mono', skipping verification.
==> Installing Cask font-victor-mono
==> Purging files for version latest of Cask font-victor-mono
Error: It seems the Font source '/usr/local/Caskroom/font-victor-mono/latest/OTF/VictorMono-ItalicBold.otf' is not there.

~/Development/workcation-splash via ⬢ v11.10.0
➜ brew cask install caskroom/fonts/font-victor-mono                                                          11:47:36 PM
==> Satisfying dependencies
==> Downloading https://rubjo.github.io/victor-mono/VictorMonoAll.zip
Already downloaded: /Users/evansparkman/Library/Caches/Homebrew/downloads/43b6f0d85f1a05524cab0ba69b5100f5a94726ed197cdb3d8d17d024da9d7b35--VictorMonoAll.zip
==> No SHA-256 checksum defined for Cask 'font-victor-mono', skipping verification.
==> Installing Cask font-victor-mono
==> Purging files for version latest of Cask font-victor-mono
Error: It seems the Font source '/usr/local/Caskroom/font-victor-mono/latest/OTF/VictorMono-ItalicBold.otf' is not there.

**Comment by rubjo** [comment]
Ah, that’s right, I’ll make a pull request to fix the issue. Thanks for notifying me.

**Comment by rubjo** [comment]
Will work once https://github.com/Homebrew/homebrew-cask-fonts/pull/1850 is merged.
