### ISSUE TITLE
'6' and '9' like SF Mono or JetBrains Mono

### ISSUE THREAD

**Issue by chrysos349** [rubjo/victor-mono#132]
Hi,

Thanks a bunch for designing this font.

Could you add variant glyphs for `6` (number six) and `9` (number nine) similar to `SF Mono` and `JetBrains Mono`?

![SF Mono and JetBrains Mono](https://i.imgur.com/1g8h58l.png)

**Comment by rubjo** [comment]
Yes, I can. Slated for next release (although in a bit of a hiatus right now, so will collect some more changes before any new version will be made).

**Comment by rubjo** [comment]
(This is stylistic set ss07 from version 1.5.3 onwards) 👍
