### ISSUE TITLE
Question: How can I add my own ligatures to Victor Mono?

### ISSUE THREAD

**Issue by iCraft85** [rubjo/victor-mono#136]
So I just wanted to know how I could add my own infinite length ligatures to Victor Mono? because I wanted to have infinite length `_______` cuz I need it for my terminal prompt but I am not really sure how I would go about adding it

**Comment by rubjo** [comment]
I don’t know, as I haven’t seen it as particularly valuable myself.

You could check Fira Code’s source files to see how it’s implemented there. And be aware that there are some issues preventing infinite ligatures from rendering perfectly at all times: https://github.com/tonsky/FiraCode/issues/1081
