### ISSUE TITLE
Add more arrows?

### ISSUE THREAD

**Issue by librarianmage** [rubjo/victor-mono#137]
It would be pretty cool if the font supported more of the [Arrows Unicode Block](https://codepoints.net/arrows). Particularly, I wanted to use ↩ as a new line glyph.

**Comment by rubjo** [comment]
Hi, learned & magical librarian, thanks for the input. I agree, would be nice to complete this block. Should be pretty straightforward (what's not is finding time to do it). Marking it for next release, don't really know when it will happen yet. 🙂

**Comment by librarianmage** [comment]
Appreciate the response! I feel you wrt trying to find the time to do things
