### ISSUE TITLE
Would you consider adding ligature `:<`?

### ISSUE THREAD

**Issue by singularitti** [rubjo/victor-mono#138]
Glad we have such a good font!
I saw that we have `:>`, `:<`, and `>:`, but there seems to be no `<:`, which is used pretty often in languages like [Julia](http://docs.julialang.org/en/v1/base/base/#Core.:%3C:). Would you mind adding it? That will be of great help, thank you!

<img width="130" alt="image" src="https://user-images.githubusercontent.com/25192197/174623305-2da4967e-0a02-4c33-8321-36139191f668.png">

**Comment by rubjo** [comment]
I have considered it, and I will :)

Don’t know when next release will be though, could be anywhere from one week to a couple of months. :)

**Comment by singularitti** [comment]
Cool, thanks!
