### ISSUE TITLE
What is the theme used in the example code previews?

### ISSUE THREAD

**Issue by ejuarezg** [rubjo/victor-mono#139]
The theme doesn't quite look like the Victor Mono linked on themer.dev, although I may be wrong.

I apologize if the question is irrelevant to the project. I didn't know where else to ask.

**Comment by rubjo** [comment]
I'm behind both the site and the themer.dev theme, so it's the right place to ask :)

It's also a good question. I have made a few themes:
- The code themes (dark and light) used on https://rubjo.github.io/victor-mono/
- The Ultimate Dark Neo code editor themes for VS Code and Sublime Text:
  - https://marketplace.visualstudio.com/items?itemName=rubjo.ultimate-dark-neo
  - https://open-vsx.org/extension/rubjo/ultimate-dark-neo (alternative to the first one)
  - https://packagecontrol.io/packages/Ultimate%20Dark%20Neo
- The Victor Mono theme on https://themer.dev/victor-mono

They all vary slightly: they weren't all made at the same time, and I like to change things up a little. 😁 The editor themes have slightly more muted colours than on the web site (which started out as a Oceanic Next theme and was heavily modified for the CodeMirror in-browser code editor), and the themer.dev theme doesn't have any italics (only supports colours, as far as I know).

Your best bet to end up with exactly what matches your preference is probably to start with a theme which has some things you like, and then learn how to tweak things to your exact liking for the editor you use. One size doesn't fit all when it comes to themes. Some people prefer light themes, others monochromatic ones, some even pay good money to get [neon-like ones](https://draculatheme.com/pro).

Personally, I've used Ultimate Dark Neo for Sublime Text for a couple of years now, and it has settled as the theme I like to look at every day :)

**Comment by ejuarezg** [comment]
Thanks for the detailed response. I'm going try out Ultimate Dark Neo code when I get the chance. I like the muted, pastel colors. Much easier on the eye :) Feel free to close this issue now.

**Comment by sonulohani** [comment]
@rubjo 

I am using VictorMono in Qt Creator and I see font very thin

![image](https://user-images.githubusercontent.com/2958681/190320263-ab728912-31ba-4493-9a8a-6e864569db52.png)

Compared to the one you've shown in the README, seems like you're using either medium or semibold. The below image is using VictorMono Semibold and I dont see VictorMono Semibold Italic variant being used. Seems like some issue with font engine figuring out the italic variant 

![image](https://user-images.githubusercontent.com/2958681/190320674-2dc5639c-598f-4d76-b153-5e368bd67272.png)

**Comment by rubjo** [comment]
@sonulohani Yes, this is probably Qt Creator not being able to identify/find SemiBold Italic. The readme examples uses a heavier variant than Normal, yes, because I realize that many people don't have high-DPI screens and anyway prefer a heavier style than I do.

You should probably file a bug over at https://bugreports.qt.io/secure/Dashboard.jspa, a quick search reveals lots of issues related to missing / faux italics.
