### ISSUE TITLE
Box drawing issues

### ISSUE THREAD

**Issue by Badokas** [rubjo/victor-mono#142]
Hello,

First of all, thanks for the font! I love it.

I've noticed some spacing / alignment issues with character ▼
```
BLACK DOWN-POINTING TRIANGLE
Unicode: U+25BC, UTF-8: E2 96 BC
```
<img width="298" alt="Screenshot 2022-08-25 at 17 36 54" src="https://user-images.githubusercontent.com/32526275/186695361-8bf68f2f-e80d-468c-8943-00e4470d1b7c.png">

The alignment issue can be easily seen in longer lines:
<img width="332" alt="Screenshot 2022-08-25 at 17 37 41" src="https://user-images.githubusercontent.com/32526275/186695403-0dcbc112-a11d-40a8-9249-208e933df6ac.png">

Is there anything I could do to fix it?

**Comment by rubjo** [comment]
Hi, yes, that's because that glyph isn't added to the font yet, so your system uses a default fallback font - which doesn't perfectly align with Victor Mono.

I'll probably add all the glyphs from the Geometric Unicode block (https://en.wikipedia.org/wiki/Geometric_Shapes_(Unicode_block)) at some point.

**Comment by rubjo** [comment]
Released in 1.5.5.

**Comment by Badokas** [comment]
Thank you!

**Comment by Badokas** [comment]
I love it :)

<img width="847" alt="Screenshot 2023-07-13 at 15 06 56" src="https://github.com/rubjo/victor-mono/assets/32526275/6be432f3-acd3-4116-8d7c-963ba869ffaa">

**Comment by Wukuyon** [comment]
@Badokas, that’s an incredibly cool text diagram. It would be fantastic for testing other monospace fonts. Could you please share its origin and provide a text version here?
