### ISSUE TITLE
Weird "===" look in VS Code

### ISSUE THREAD

**Issue by safarli** [rubjo/victor-mono#143]
Hello there, I came across a weird problem in VS Code using 'Victor Mono' font.
My settings are:

```json
 "editor.fontFamily": "Victor Mono",
  "editor.fontSize": 13,
  "editor.fontLigatures": true,
```

---

I've tested it in fresh installation of VS Code, but no luck.

Look at the "===" ligatures:
![Code_ybjsSVeu2q](https://user-images.githubusercontent.com/65605198/189544899-0eccce99-ade3-4d7c-9ea4-90f57a503193.png)

**Comment by rubjo** [comment]
Yeah, this is a known issue with the font (and other fonts) on low-resolution displays in certain operating systems. I don’t know how to fix it, unfortunately.
