### ISSUE TITLE
How about a walrus ligature for python's assignment operator? 

### ISSUE THREAD

**Issue by MrDowntempo** [rubjo/victor-mono#145]
Here's a small feature request. In Python there is something called the [walrus operator](https://docs.python.org/3/whatsnew/3.8.html?highlight=walrus) which is := because it looks like a little walrus on its side with 2 eyes and 2 tusks. In Victor Mono it looks decidedly un-walrus-y because the tusks (the =) is skewed  above both eyes. Even here on GitHub, they're not perfectly centered with each other, but at least the tusks are between the eyes. 

I deally the equals would stay in place, but the eyes would be spaced out more and centered with the eyes. But there's probably a little room for creativity and maybe even a little cuteness.

**Comment by rubjo** [comment]
https://user-images.githubusercontent.com/42270947/200325810-f76f6a1e-da0a-4df4-bb05-173bdf2cffc2.mov

?

**Comment by MrDowntempo** [comment]
Looks fantastic!

**Comment by MrDowntempo** [comment]
![walrus](https://user-images.githubusercontent.com/8398380/200366722-b3383476-ed33-47a6-b27b-622776573857.png)
I gave it a shot and it was a very subtle difference. Maybe not needed at all. Or maybe the dots need a bit more space. I'm happy either way.

**Comment by rubjo** [comment]
Thanks for the input, for now I'll leave this as it is :)
