### ISSUE TITLE
Visual Studio without ligatures

### ISSUE THREAD

**Issue by robindegen** [rubjo/victor-mono#146]
I'm sorry if this is actually documented somewhere; but I can't seem to find it. Visual Studio (not code; regular visual studio) does not provide a way to disable ligatures but from what I can see, all fonts in the download contain them. Microsoft simply says "use a font without ligatures if you don't want them".

Is there a version of the font without them? I like the font itself but i find the ligatures difficult to read.

**Comment by rubjo** [comment]
Hi!

See this issue:

https://github.com/rubjo/victor-mono/issues/118
