### ISSUE TITLE
Build with slashed zero as default?

### ISSUE THREAD

**Issue by nathanielevan** [rubjo/victor-mono#147]
Hi, loving the font so far, much appreciated! Hope this isn't too big of a request, but would it be possible to have a build with the slashed zero (ss02) as default, or is there a way to build it myself? I'm aware that you can select your preferred stylistic set with fontconfig on Linux, however I don't think it's very consistent (LibreOffice and Firefox continued using the default dotted zero variant, while it worked in Zathura), in addition to that I patch my fonts with Nerd Fonts and it strips off all alternative stylistic sets, if I remember correctly.

**Comment by rubjo** [comment]
Hi!

Thanks for trying the font!

Here's a quick export for you:
[0.zip](https://github.com/rubjo/victor-mono/files/10168249/0.zip)

**Comment by nathanielevan** [comment]
Thanks mate, much appreciated!

**Comment by nathanielevan** [comment]
Hi again, I think I figured something out with FontForge, but upon exporting I was met with this message: "The points in uni049F are not numbered properly. This means that any instructions will probably move the wrong points and do the wrong thing. Would you like to remove the instructions?" I'm completely unfamiliar with manual font building and hoping you might be familiar with this error/prompt:
![scshot-071222-074959](https://user-images.githubusercontent.com/9361126/206060480-5b2de2c7-b283-4e43-9268-e96cb2ed972e.png)

**Comment by rubjo** [comment]
Did you want more changes apart from the slashed zero? Sorry, I am not familiar with FontForge at all.

**Comment by Finii** [comment]
> but would it be possible to have a build with the slashed zero (ss02) as default

No need to become 'technical', end-user solutions for example
* https://mutsuntsai.github.io/fontfreeze/
* https://github.com/twardoch/fonttools-opentype-feature-freezer

_(From https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#baking-in-stylistic-sets-into-the-font-file)_
