### ISSUE TITLE
Conflicting stylistic sets with Fira Code

### ISSUE THREAD

**Issue by bldur** [rubjo/victor-mono#148]
Like for example `zero, cv11..cv13; ss01 for a, ss02 g, ss03  &, ss04 $, ss05 @, ss06 \\, ss07 != !~`.

Not aware of any standards here, but overlaps that change different things can be surprising.
Whatever is reserved and agreed on here by the early coding ligatures is certain to become one.
Like say, if one change a letter, that is default for another font family.

**Comment by rubjo** [comment]
Yes, I am not aware of any standards here either. As far as I know each font with stylistic sets etc define how their rules are laid out.
