### ISSUE TITLE
Cyrillic glyphs

### ISSUE THREAD

**Issue by den32ds** [rubjo/victor-mono#15]
Thank you very much for font. But I would like to be able to write comments in the code in Russian.
P. S. Where I can download Glyphs project file?

**Comment by rubjo** [comment]
Thank you for liking it!

Cyrillic: I have thought about adding these. Will probably take some time, so check back in a few months.

Download: The Glyphs project files are not available for download for the time being.

**Comment by den32ds** [comment]
Sad to hear that, I just create a list of true open source fonts.

**Comment by den32ds** [comment]
@rubjo hah, finally, Victor Mono is impressive and _open source_ typeface, made by unstoppable virtuoso. In honor of this, I will do a list of open source fonts. Happy New Year, and greetings from Russia!

**Comment by den32ds** [comment]
@rubjo on site, change "The отлично programming font" to "отличный", and add "убийственный"

**Comment by rubjo** [comment]
ok - first change: from adverb to adjective?

убийственный: murderous/deadly???

**Comment by den32ds** [comment]
Yes, from adverb to adjective. And your typeface is deadliest, isn't it? 🤙

**Comment by den32ds** [comment]
Note, "прекрасный" is right, not "прекрасно"

**Comment by rubjo** [comment]
ok, will correct these eventually - thanks for pointing it out!

**Comment by den32ds** [comment]
@rubjo hi there, it`s me again
As i said, https://github.com/den32ds/typefaceslist/blob/master/README.md
