### ISSUE TITLE
Cannot be used on jetbrains IDE such as Pycharm

### ISSUE THREAD

**Issue by wwweww** [rubjo/victor-mono#157]
After I checked the previous issues, I tried in vain to release this issue. I used the version of Pycharm2023.1.

**Comment by rubjo** [comment]
https://github.com/rubjo/victor-mono/issues/113 ?

**Comment by kenmcd** [comment]
> After I checked the previous issues, I tried in vain to release this issue. I used the version of Pycharm2023.1.

Try only installing these four fonts: Regular, Italic, Bold, Bold Italic
Those four fonts have the style group configured properly.

All the other weights have mis-configured style groups which are sure to confuse applications and users.

To use the Oblique fonts, rather than the Italic fonts, would require modifying (fixing) the fonts.

**Comment by gabrielizalo** [comment]
This worked for me: I installed obliques and NO italics.
I mean install: Regular, Oblique, Bold, Bold Oblique

**Comment by rubjo** [comment]
@wwweww Can this be closed? What have you tried? What didn’t work?

**Comment by kenmcd** [comment]
This issue should not have been closed.
The fonts available in the v1.5.5 release here are badly broken.
They are not going to work properly in many applications.

The easiest fix is to get the versions from Google Fonts.
Those fonts have been fixed and should work properly.
https://fonts.google.com/specimen/Victor+Mono

**Comment by rubjo** [comment]
Well, I use them in many applications. And they work.

But if the Google Fonts version works better in your use case, by all means use that.

**Comment by agingorange** [comment]
> Try only installing these four fonts: Regular, Italic, Bold, Bold Italic
> Those four fonts have the style group configured properly.

Thanks. This worked for me in the Jetbrains IDEs. Neovim had no problems.
