### ISSUE TITLE
Font needs to be reinstalled on Windows every reboot w/VS Code

### ISSUE THREAD

**Issue by ryanspice** [rubjo/victor-mono#158]
I have to reinstall the font and reopen vscode every reboot or else I cant use the font. Any ideas?

**Comment by kenmcd** [comment]
Do not use the Install button in the Windows Font Viewer to install fonts.
That will install the fonts in your User Fonts folder.
This causes issues with vscode.
Un-install the fonts.
Then install the fonts for All Users.
- Select the font files
- Right-click
- Select _Install for all users_

This will install the fonts in the main Windows Fonts folder.
Then vscode should be fine.

**Comment by ryanspice** [comment]
Seems to have worked! Thanks. (no thanks to windows 11 for hiding that button in it's second context menu thing lol)
