### ISSUE TITLE
A weird gibberish in fish's command info text(italics)

### ISSUE THREAD

**Issue by olivertzeng** [rubjo/victor-mono#159]
![image](https://github.com/rubjo/victor-mono/assets/86348833/4c981f19-3004-494f-b30c-2289d8d26081)

**Comment by olivertzeng** [comment]
> The terminal, whichever it is, seems to struggle with ligatures. Open an issue there, maybe?

Konsole

**Comment by rubjo** [comment]
OK, so I would open an issue on their tracker / forums - or maybe just not install the italics to make the app/renderer use the normal style or faux italics. Or use a different terminal.

**Comment by olivertzeng** [comment]
> OK, so I would open an issue on their tracker / forums - or maybe just not install the italics to make the app/renderer use the normal style or faux italics. Or use a different terminal.

Ok
