### ISSUE TITLE
It's too thin (again)

### ISSUE THREAD

**Issue by chmielcode** [rubjo/victor-mono#160]
Well... knowing that the answer to "it's too thin" is "yes" I would like to ask you if you maybe know a way to thicken this font up a notch using a script. By that I mean making Medium to be recognized as Regular. This font is fantastic, but just too thin for me. I've tried experimenting with font-tools and fontforge, but I'm an amateur when in comes to changing font metadata, so I've failed miserably. If you have any hints, I would be thankful. If not, maybe I'll figure it out eventually :)
Thank you for your work!

**Comment by rubjo** [comment]
🙂 Yes, I know it’s thin to some (most) people’s liking.

You could try not installing the regular weight, only medium or semibold? 🙂

**Comment by chmielcode** [comment]
Thank you. Unfortunately I've already tried that and this solution isn't perfect. After installing Medium, MediumItalic, Bold and BoldItalic weights Notepad++ gets confused. Font list contains "Victor Mono" and "Victor Mono Medium" - as if it's a separate family. In this case "Victor Mono" is the Bold weight, and "Victor Mono Medium" 'family' does not have bold option.

**Comment by rubjo** [comment]
I've done a quick one-off export for you where the lighter weights have been fattened up. The difference between each weight is now very small, but in return, the Regular weight is here approximately where Medium is at in the official version. :)

[Victor Mono Fat Edition.zip](https://github.com/rubjo/victor-mono/files/13066616/Victor.Mono.Fat.Edition.zip)

**Comment by chmielcode** [comment]
Oh my! It looks great :) Thank you! Usually ttf renders better on Windows, but even then otf version you provided looks quite nice. Closing it and hoping that all other "too thin" malcontents find this version. Best of luck!

**Comment by sanyer** [comment]
oh, this is much better for the light themes, thanks @rubjo
