### ISSUE TITLE
Requesting Variable <3

### ISSUE THREAD

**Issue by coycoylaniba** [rubjo/victor-mono#162]
It would be nice if Victor Mono has a variable variant <3 Love your font!

**Comment by rubjo** [comment]
Hi, thanks ❤️ 

Try the Google Fonts distribution: https://fonts.google.com/specimen/Victor+Mono?classification=Monospace&preview.text=%3D%3D%3E%20Hi%20coycoylaniba!%20%3C%3D%3D

**Comment by coycoylaniba** [comment]
thanks!
