### ISSUE TITLE
How to Disable Cursive on VS Code

### ISSUE THREAD

**Issue by ragurney** [rubjo/victor-mono#163]
Hello, 

I love the font but would like to disable cursive. Could you point me to documentation on how to do this in VS Code, I'm having trouble finding any.

**Comment by ragurney** [comment]
I solved this by installing only Victor Mono Regular and Victor Mono Oblique in my mac, and setting the font to Victor Mono. If that's the best way to do it feel free to close this issue!

**Comment by mikemklee** [comment]
Also was looking for a way to do this, your suggestion worked like a charm. Thanks!
