### ISSUE TITLE
Victor Mono in google colab

### ISSUE THREAD

**Issue by h4ck4l1** [rubjo/victor-mono#164]
Hello,
How do I enable Victor Mono in google colab?
Thankyou.

**Comment by rubjo** [comment]
Never used it, but as a test just now this worked for me (on macOS):
- Open Colab
- "Tools" menu (or whatever the second last menu item is called in English)
- "Editor" tab (or whatever tab no 2 is called)
- Write "Victor Mono" for "Font family" (or whatever setting no 3 is called)

:)

**Comment by rubjo** [comment]
That looks like Windows. That's the same setting I use.

"Victor Mono" worked for me on a Mac. You could try "VictorMono" or other variants maybe.

**Comment by h4ck4l1** [comment]
Yes I will try other variants, I will get back If none worked.
Thankyou for responding right away. :)

**Comment by h4ck4l1** [comment]
After tinkering with settings and changing every font settings in MS Edge, I got the solution. If anyone stumbles here using Edge and not able to change colab font to Victor Mono

1. go to edge://flags
2. search for #edge-reading-view-text-preference
3. Enable and relaunch your browser. It overrides any font differences between your cloud IDE and installed fonts.

Thanks to @rubjo  for providing info that Victor works on MAC Colab.
