### ISSUE TITLE
Disabling turbofish ligature as a stylistic set?

### ISSUE THREAD

**Issue by waltermoreira** [rubjo/victor-mono#165]
This is a great font, and the ligatures look fantastic to my eyes (I know it's a contentious issue, and I'm on the pro-ligature side).

That said, there is one ligature that was introduced in 1.5.5 (#151) that I find very distracting, because of the striking differences between the original shape `::<>` and the fish with tail glyph.

I know I could disable the ligatures in general, but that also disables all the other ligatures that I value so much.

Is there a way to add a stylistic set option that allows to disable the turbofish ligature?

Thank you for the great work with this font!

**Comment by rubjo** [comment]
Thank you, I agree. Turbofish now only aligns things slightly by default, and the previous ligature is from version 1.5.6 assigned to ss08.

**Comment by waltermoreira** [comment]
Thank so much you for such a speedy resolution. I made a very small contribution through paypal as a symbolic token of appreciation.  Keep up the great work!

**Comment by engeir** [comment]
> I know I could disable the ligatures in general, but that also disables all the other ligatures that I value so much.

There is a way of disabling ligatures? How can that be done?

**Comment by rubjo** [comment]
It depends on what editor you use.

**Comment by engeir** [comment]
Oh like that, I see! Thank you.
