### ISSUE TITLE
weird rendering on wezterm

### ISSUE THREAD

**Issue by elbkind** [rubjo/victor-mono#168]
Hi,

i really like the font and in iTerm2 it rendered in the console without problems. However, in whezterm the font is not "centered" vertically:

<img width="327" alt="image" src="https://github.com/rubjo/victor-mono/assets/953696/c384f06d-2c8a-4b37-a0c3-d0c170c2d2e9">

Other fonts are more centered (vertically), like here (wezterm default font): 
<img width="389" alt="image" src="https://github.com/rubjo/victor-mono/assets/953696/5a637575-b527-42dc-b56a-5bcea1393b87">

I tried adding some options, but to no avail:
	harfbuzz_features = {
		"calt=1",
		"clig=1",
		"liga=1",
		"ss01=1", <-- this was your recommendation for kitty
		"ss02=1",
		"ss03=1",
		"ss04=1",
		"ss05=1",
		"ss06=1",
		"ss07=1",
		"ss08=1",
		"dlig=1",
	},

**Comment by rubjo** [comment]
Hi!

Not too sure about this. You might have better luck trying with the [Nerd Font version of Victor Mono](https://www.nerdfonts.com/font-downloads). A quick test showed better alignment in Wezterm using that one. 
<img width="987" alt="image" src="https://github.com/rubjo/victor-mono/assets/42270947/fe5072d1-9a13-488a-9b1d-b1c9533b7bad">

**Comment by elbkind** [comment]
Exactly that, thank you!
