### ISSUE TITLE
Alignment of brackets/parentheses

### ISSUE THREAD

**Issue by Emexus** [rubjo/victor-mono#19]
I love this font, but I can't get myself to get over this alignment of brackets for some reason, and it's the only thing really holding me back from using this font :(

An example of this is:
<img src="https://i.imgur.com/XaVw86l.png">

Would it be possible to remove this alignment or make it less strong?

**Comment by rubjo** [comment]
Excellent point, thanks for bringing it up. I’ll revise this for the next release in a few weeks.

**Comment by Emexus** [comment]
Can't wait, thanks a lot for taking care! 😺 
I really wish I wasn't so annoyed by this, but the inner me likes to be annoyed by every little thing

Would it actually take a few weeks though? Just wondering

**Comment by Emexus** [comment]
Thanks so much for fixing! This font is very enjoyable now :)
