### ISSUE TITLE
<= and >= ligatures missing

### ISSUE THREAD

**Issue by rderimay** [rubjo/victor-mono#2]
I do not agree about the little twist of the ff, fl and fi ligatures (part understandably) bothering (#1) some, but hey, that's your font and it should stay like that.

But , <= and >= missing ligatures are a pain in the ass and wayyyy more important  :-D :-D

btw, thanks a lot for that great work, this instantly became my PhpStorm font!

**Comment by rubjo** [comment]
Thank you so much for the kind words!

<= & >= added.

😄

**Comment by rderimay** [comment]
Many thanks for the super quick reaction!
Unfortunately, I was not clear in my text, I meant that "greater or equal" (> followed by =) and "smaller or equal" (< followed by =) should be handled as ligatures. Here an example on how it is handled in Fira Code:

![image](https://user-images.githubusercontent.com/12871929/59383040-6ce70600-8d5f-11e9-8abe-9a5239a8cbf5.png)
