### ISSUE TITLE
Cursive on VS Code

### ISSUE THREAD

**Issue by SSmale** [rubjo/victor-mono#22]
I have installed the font on a Windows 10 system and cannot get the cursive to show in ether code or the insiders build. both IDE's are up to date and using the default dark theme

**Comment by rubjo** [comment]
Hello there,

I’m not sure what (if any) parts of the code the default theme sets with italics in VS Code.

Maybe check here: https://stackoverflow.com/questions/41320848/how-do-i-get-visual-studio-code-to-display-italic-fonts-in-formatted-code

**Comment by SSmale** [comment]
Thank you that worked perfectly. might be worth adding that to the readme?
