### ISSUE TITLE
Too Thin

### ISSUE THREAD

**Issue by alfianguide** [rubjo/victor-mono#23]
font is tooooo thin almost unreadable, need to set it bold so it is readable.

**Comment by rubjo** [comment]
OK.

(Don’t really know what else to say here)

**Comment by Avi-D-coder** [comment]
I am using demi bold as my regular font, this works great, but full bold is a little hard to distinguish. A heavy bold would be a great addition to this font.

**Comment by alfianguide** [comment]
No idea

**Comment by rubjo** [comment]
Couple of issues here.

I prefer thin fonts, so Victor Mono’s default is thinner than most other fonts. I also know most other fonts have a «fatter» bold than VM’s Bold.

For the next release, I’ll try to see if the font shapes can be made even more bold without curves and other features being misaligned/made unrecogniseable.

As for broken ligatures, I’m not aware of that, but I do know that VS Code on macOS Catalina currently has a bug that only shows italics when using a single font weight (600, I believe).

**Comment by alfianguide** [comment]
Thx

**Comment by xvrdm** [comment]
It's more prose related than code related, but so far, it looks like Victor Mono really has the perfect x-height to be mixed with common serif/sans-serif fonts. In that context, I think a "fatter" bold would be a great addition.
