### ISSUE TITLE
Weird font size issue in windows terminal

### ISSUE THREAD

**Issue by offero** [rubjo/victor-mono#24]
![image](https://user-images.githubusercontent.com/4681330/62586238-bc8f0d00-b88a-11e9-99ec-a591634e8cd9.png)

I'm not sure why this happens, but in my Windows Terminal this happens to some of the entries. Any ideas?

Windows Terminal (Preview)
Version: 0.3.2142.0

**Comment by rubjo** [comment]
I see the same, and have never seen it anywhere else.

I have no idea why this happens. It could very well be some setting/parameter in the font, although to me, the intersection of Windows, font rendering and prerelease software doesn't bode spectalularly well.

Maybe there's more to be found somewhere in the ~600 open issues, eg. [MEGA THREAD: Design is not complete, UI is not polished](https://github.com/microsoft/terminal/issues/1375)
