### ISSUE TITLE
Small ф not proportional to other letters

### ISSUE THREAD

**Issue by den32ds** [rubjo/victor-mono#25]
![изображение](https://user-images.githubusercontent.com/24569064/62614299-c9a40e80-b913-11e9-8dce-177b09d97f26.png)

**Comment by den32ds** [comment]
And still waiting to original Glyphs project files :)

**Comment by rubjo** [comment]
Ah, I see, thanks. I'll fix this issue in the next release.

> And still waiting to original Glyphs project files :)
Keep waiting. 😛 The .glyph files contain notes and annotations to myself, and I'm not making them available for now. If you have bought the software, you have probably noticed you can open regular font files with it.
