### ISSUE TITLE
"fi" and "fl" ligatures render incorrectly in MacVim

### ISSUE THREAD

**Issue by zatchheems** [rubjo/victor-mono#27]
##  Background

hello! since switching from terminal Vim to MacVim, I've noticed that `fl` and `fi` render improperly, making text such as `fixme`, `fluid`, and `config` illegible and messing up the rest of the line.

within MacVim, a similar issue has been raised for a different font, albeit for different characters: https://github.com/macvim-dev/macvim/issues/841

I have been unable to replicate this issue with any other font on my machine that uses ligatures, so I'm curious as to whether this is not a MacVim-specific rendering problem, whether similar behavior can be replicated, and whether this is the correct place to make note of it.

given the discussion on whether the ligatures in question should be included at all, this issue slightly relates to: https://github.com/rubjo/victor-mono/issues/1

thanks!

##### `set macligatures`
![image](https://user-images.githubusercontent.com/8506829/62899012-73243f00-bd1c-11e9-8e57-79cd5e816817.png)

##### `set nomacligatures`
![image](https://user-images.githubusercontent.com/8506829/62898993-669fe680-bd1c-11e9-9492-b84d6eefa651.png)

**Comment by rubjo** [comment]
Kudos for being one of the Vim people! Every time I try a derivative, I think "gee, I'll have to use a year to learn how to get productive using this". 😆

MacVim has problems drawing more of this font's ligatures, it seems (eg. >= and <=).

It wil probably work better if I change the way ligatures are set up. At the moment, I don't have an ETA on this.

**Comment by zatchheems** [comment]
thanks for getting back to this so quickly! I figured this had more to do with MacVim than anything given that everything renders hunky-dory in iTerm2:

![image](https://user-images.githubusercontent.com/8506829/62967339-5fd1ac00-bdce-11e9-8b38-c1a5f98e1d47.png)

I can live with it for now. cheers!

**Comment by rubjo** [comment]
Cool, iTerm2 is what I use as well. Leaving issue open and retesting with MacVim after next release.
