### ISSUE TITLE
<= & >= ligatures are wrong

### ISSUE THREAD

**Issue by rderimay** [rubjo/victor-mono#3]
Many thanks for the super quick reaction to issue #2 
Unfortunately, this is embarrassing, I think I was not clear in my text, I meant that "greater or equal" (> followed by =) and "smaller or equal" (< followed by =) should be handled as ligatures. 
Here an example on how it is handled in Fira Code:
![](https://user-images.githubusercontent.com/12871929/59383040-6ce70600-8d5f-11e9-8abe-9a5239a8cbf5.png)

Sorry for the confusion.

**Comment by rubjo** [comment]
Ah, no problem, I see what you mean. It's coming back to me why they weren't included in the first version: I started wondering if at small sizes, it might be too easy to overlook a Fira Code-like <= for < (maybe not a problem with adequate spacing). And then I just forgot about it. :)

Also, Fira Code has a glyph that is almost single-char-width, while eg. Monoid and others solve it like this:
<img width="411" alt="Monoid" src="https://user-images.githubusercontent.com/42270947/59406657-346f1880-8daf-11e9-8acf-66fd443a1c74.png">

I'll see if I come up with something that fits in.

**Comment by rderimay** [comment]
I think personally that the variant with the bottom bar at an angle looks way better than the one with the bottom bar being horizontal and would better fit the sleekness of you font. Before using your font, I was using Fira Code even in small sizes with no problem, but others could think different of course

**Comment by rubjo** [comment]
Since you used the term "Victor Mono era", I'll do this. 😄  Solving it similarly to Fira Code some time in the coming days.

**Comment by rderimay** [comment]
:-) Thanks !
