### ISSUE TITLE
Bold "E" in some sizes looks odd

### ISSUE THREAD

**Issue by Emexus** [rubjo/victor-mono#30]
Example:
<img src="https://i.imgur.com/YhX6a3V.png"/>

This only happens in some font size, I'm using this in VS Code, hope that it isn't VSC causing the issue. If further info is needed, I'll be happy to give them!

**Comment by rubjo** [comment]
Hi,

Thank you for letting me know! Would you care to retest with the latest version and close this issue if it looks OK now?

**Comment by Emexus** [comment]
Looks perfectly fine now!
