### ISSUE TITLE
Make nicer ampersand

### ISSUE THREAD

**Issue by klippx** [rubjo/victor-mono#31]
I think the ampersand looks a bit odd, it does not follow the same nice style as the rest of the font. "&&" style of writing code is quite common in any language and making them nicer would be worth it. 

Example:
![Screenshot 2019-08-27 at 15 39 26](https://user-images.githubusercontent.com/2785359/63776046-e1eac600-c8e0-11e9-9c1e-e2edb1895eb4.png)

But maybe that's only me?

**Comment by rubjo** [comment]
Aahh, the ampersand, a typophile’s favourite playground. I’m actually pleased with the way they turned out (and the understated just-prolonged connecting line for the && ligature). Then again, I can probably be convinced to revise it or at least try. :)

There are so many directions to go here: what ampersands / style is «nicer»? And what best retains legibility at small sizes while being decidedly distinct from other characters? Maybe it should have be a bit wider and spacious.

**Comment by klippx** [comment]
I am not a typophile, but there is something about the ampersand that I can't put my finger on: It feels narrow both at the top and at the bottom. I feel it should grab more space, so just like you put it "a bit wider and spacious" would indeed be the right direction in my opinion.

I used Fira Code a lot, I like their ampersands. Maybe some people wouldn't agree that they are decidedly distinct from the number 6 or 8, but here is a comparison for reference:

![Screenshot 2019-09-02 at 08 30 09](https://user-images.githubusercontent.com/2785359/64094451-0a991280-cd5c-11e9-88bf-5f963bad2b2f.png) (Fira Code)
![Screenshot 2019-09-02 at 08 29 54](https://user-images.githubusercontent.com/2785359/64094452-0a991280-cd5c-11e9-8871-a31dcd0e9db3.png) (Victor Mono)

I really like how Fira Code's ampersand is wide both on top and bottom; it feels "proportional" (keyword) to other letters/characters. Victor Mono's ampersand feels too "cursive" and narrow... Especially the top half of it. I guess the top half looks is a result of certain decisions made in the design of the bottom half. 

Perhaps it doesnt need to have the stroke begin in the bottom right corner?

Maybe you could try to make it similar to theirs but with a Victor Mono personality that fits your style?

Some frame of reference here: https://ampersand.gallery/
- Victor Mono is kinda close to "Palatino" style. This is in nature leaning / slanting and has a cursive feel and maybe not is the best model for a monospace style?
- Fira Code is closer to "Trebuchet MS". This has a wide/round style, no slanting. Good model for monospace ampersand imo.
- Another option would be "Verdana" style. This feels well rounded, not slanting or cursive. I can see it working for Victor Mono.

**Comment by rubjo** [comment]
Thanks for your input! I'll have a look at this at some point.

I'll probably go for making the existing shape less cursive-like and more open - nice and fancy as the curves are in the Fira Mono / Trebuchet approach, I don't feel that way of solving it is recogniseable enough, especially at small sizes.

**Comment by rubjo** [comment]
I ended up deciding I wanted a slight change - it's at least less bottom-heavy and slanted now.
