### ISSUE TITLE
VictorMonoAll was not updated

### ISSUE THREAD

**Issue by radmen** [rubjo/victor-mono#34]
Hey,

I got a notification that v1.2.6 was released. To build the AUR package I was using [VictorMonoAll.zip](https://github.com/rubjo/victor-mono/blob/master/public/VictorMonoAll.zip) archive located in public/ directory.

This time this file was not updated. I assume it's just a simple mistake, yet wanted to let you know. Could you update this archive so I can build the AUR archive with the newest version?

Thanks!

**Comment by rubjo** [comment]
Hey, thanks for noticing and telling me! :D

I’ll fix it straight away.



Kind regards from
Rune Bjørnerås

**Comment by radmen** [comment]
Thanks!

**Comment by radmen** [comment]
@rubjo I've noticed that v1.2.7 is out. Just wanted to let you know that the same thing has happened.

```
❯ sha256sum victor-mono-1.2.6.zip victor-mono-1.2.7.zip
14ede192570e6b422e9ed66bf76c9adb28dc56bdd52a83d44115d31737f1a037  victor-mono-1.2.6.zip
14ede192570e6b422e9ed66bf76c9adb28dc56bdd52a83d44115d31737f1a037  victor-mono-1.2.7.zip
```

**Comment by rubjo** [comment]
Hi again,

And thanks for telling me yet again. 😄 

Are you sure it's not a cache issue or something?

**Comment by radmen** [comment]
> Are you sure it's not a cache issue or something?

I'm using the following URL to fetch the font:

```
https://github.com/rubjo/victor-mono/raw/$_refcommit/public/VictorMonoAll.zip
```

where `$_refcommit` is the release tag - `1.2.7`.

I couldn't fetch this before the release so I'm pretty sure that this is not the cache issue :)

**Comment by rubjo** [comment]
But I am getting v1.2.7 when I do that, don’t you?

**Comment by radmen** [comment]
@rubjo I'm sorry. There was actually a bug in the build script which I just spotted. There was hardcoded git commit --,--

**Comment by rubjo** [comment]
Nothing to be sorry for 👍
