### ISSUE TITLE
Centering the ":" (colon) character

### ISSUE THREAD

**Issue by Emexus** [rubjo/victor-mono#36]
This is a suggestion where I'm quite unsure about how much others would like it, I often see the ":" aligned more lower, but it always looks a little off to me at least.
If wanted, this change would be neat to have :)

Current alignment examples:
![image](https://user-images.githubusercontent.com/20151443/64729529-9e49ac00-d4dd-11e9-864a-68333b95731b.png)

**Comment by rubjo** [comment]
I think this has crossed my mind as well actually, but I haven't decided on making any adjustments. 

It's interesting to see how different fonts position punctuation differently (on eg. app.programmingfonts.org). Although most seem to use the x-height for the colon, there's some variation. Fira Code even seems to attempt to do some "corrections" on both horisontal and vertical position depending on preceding/following characters.

In any case, changes for the colon isn't likely to come without a revision of all punctuation glyphs. I'll think about it.
