### ISSUE TITLE
White spaces are not aligned correctly

### ISSUE THREAD

**Issue by useful-friend** [rubjo/victor-mono#37]
Why is it happening?
Victor mono font:
![font test](https://user-images.githubusercontent.com/26714341/65218506-db103700-dacb-11e9-990f-56d7e8b8bd53.png)
Other monospace fonts:
![font test2](https://user-images.githubusercontent.com/26714341/65218507-db103700-dacb-11e9-8525-e7b669085aa2.png)

**Comment by rubjo** [comment]
Good question. That looks like Windows font rendering - any other details you can share about setup / app?

**Comment by useful-friend** [comment]
The app is **QtCreator** and I currently use it on **windows 10**.

**Comment by rubjo** [comment]
I'm not able to reproduce this, so I need:
a) Version (and what weights/styles) of the font installed
b) Exact steps on how to get to something that looks like that screenshot
c) Settings / name of syntax theme used

**Comment by useful-friend** [comment]
I have only installed `VictorMono-Italic.ttf ` and `VictorMono-Regular.ttf`
The version is 1.260.
I was previously using sourceCodePro font and only changed the font in the settings.
In the preferences I added italic to those parts I wanted to be cursive.
for example to `PrimitiveTypes`, `Type`, `local`, `function `and some others.
The theme is `flat dark` and the color scheme is `inkpot` if it matters.
It might be a problem with the `QtCreator`.

**Comment by useful-friend** [comment]
![image](https://user-images.githubusercontent.com/26714341/65250361-b4252580-db0a-11e9-9c0c-c63a85061f25.png)
The problem is gone by removing the bold property from the cyan colored parts.
Does this shine any light on the matter?

**Comment by rubjo** [comment]
Yes, I suspect you can also re-enable the bold style in the theme as long as you have the bold style installed - I think QtCreator incorrectly increases the width of the faux bold style.

**Comment by useful-friend** [comment]
Yes you are right. installing italic bold font file fixed the problem.

**Comment by rubjo** [comment]
No problem, good to hear it’s OK now. 👍🏻
