### ISSUE TITLE
:: ligature request (tighter spacing)

### ISSUE THREAD

**Issue by mingaldrichgan** [rubjo/victor-mono#38]
Thank you for this amazing font! I'm curious if you've considered, or would consider, adding a ligature for `::` with tighter spacing between the two colons (like Fira Code does)?

**Comment by rubjo** [comment]
Sure, why not. To be included in the next release.

If there are other character combos that you feel could benefit from being ligatures, feel free to make some more issues.

**Comment by mingaldrichgan** [comment]
> If there are other character combos that you feel could benefit from being ligatures, feel free to make some more issues.

Coming from Fira Code, I'm tempted to say that parity with their ligatures would be nice but I'm sure you don't agree with all of their decisions. 😄

**Comment by rubjo** [comment]
As I’d like to create them from scratch, it’s mainly a fair bit of work and will have to be done in stages.

I don’t know if I’m going to go down the «make any possible combo a ligature» path. I’m questioning the usefulness / added value for some of the ligatures - although I guess that’s a common sentiment against ligatures in general.

I’ll try to make a list of a handful of ligatures it is natural to start with, and include those in the next release.

**Comment by tomByrer** [comment]
>  I’m questioning the usefulness / added value for some of the ligatures

I find ligatures for `!=`,  `=>` & `===` super helpful when scanning code.  `<=`, `>=`, & `<!--` are also helpful.  I keep expecting a `/>` ligature, though I can not say it is much use.

I don't find your `:=` helpful, since my eyes make it look like `*=`.  I like Fira's exaggerated `:` , `;` & `:=` since those characters I use often.

**Comment by rubjo** [comment]
:= is slated to be less cramped in the next release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
