### ISSUE TITLE
Submit the font to homebrew-cask-fonts

### ISSUE THREAD

**Issue by jtiala** [rubjo/victor-mono#4]
I for one would love to install the font from homebrew. Makes keeping it up to date so much easier. Don't really know what it involves and if it's too much work to keep up to date in brew, tho.

https://github.com/Homebrew/homebrew-cask-fonts

Very nice font btw, good work!

**Comment by rubjo** [comment]
Excellent suggestion, will do.

**Comment by rubjo** [comment]
Done: `brew cask install font-victor-mono`

**Comment by klippx** [comment]
When updating, how do I make sure the latest fonts are picked up? I seem to recall something about clearing font cache and whatnot. Would be cool if someone who knows added steps for it and perhaps even to the wiki/readme.

**Comment by rubjo** [comment]
Yeah, I don’t really know how brew handles that/necessity of clearing the font cache.

What I **will** try to remember for future releases, though (next one still a few weeks off), is to actually update the .zip brew looks for. Think I might have missed that sometimes...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
