### ISSUE TITLE
Font rendering of capitalized italics is buggy

### ISSUE THREAD

**Issue by cloudhead** [rubjo/victor-mono#44]
Hey there,

I've been trying to figure out why some capital italic letters are cut off or render smaller, eg. see letter 'Q' here:

![img](https://user-images.githubusercontent.com/40774/66274804-76eac280-e882-11e9-896c-8675c7a6cf98.png)

I opened an issue on kitty (the terminal I use): https://github.com/kovidgoyal/kitty/issues/2028 - but it seems like the problem is with the font.

Quoting from the kitty docs:

> The number of cells a unicode character takes up are controlled by the unicode standard. All characters are rendered in a single cell unless the unicode standard says they should be rendered in two cells. When a symbol does not fit, it will either be rescaled to be smaller or truncated (depending on how much extra space it needs). This is often different from other terminals which just let the character overflow into neighboring cells, which is fine if the neighboring cell is empty, but looks terrible if it is not.

> Some programs, like powerline, vim with fancy gutter symbols/status-bar, etc. misuse unicode characters from the private use area to represent symbols. Often these symbols are square and should be rendered in two cells. However, since private use area symbols all have their width set to one in the unicode standard, kitty renders them either smaller or truncated. The exception is if these characters are followed by a space or empty cell in which case kitty makes use of the extra cell to render them in two cells.

**Comment by rubjo** [comment]
> the problem is with the font

Well, that's arguably a question of definition. At any rate, it seems convenient for @kovidgoyal to dismiss the issue with "the font is buggy" 😄. What about the H and M?

I'm afraid you have to use a different font, or use the oblique style instead of the italic one. Alternatively, use a terminal which is able to render the glyphs (which seems to be most other terminals).

**Comment by kovidgoyal** [comment]
Oh is monospace now a subjective term? A monospace font is one that has all its glyphs, and certainly its major glyphs, having *equal* advances. If you make a font whose italic variant is not metric compatible with its regular variant, then the family cannot be called monospace.

**Comment by cloudhead** [comment]
If the font doesn't adhere to unicode standards, then it is bound to not work properly on all terminals that comply to unicode. If that's by design, it's unfortunate but it's your choice. Furthermore, Kitty is one of the few terminals out there that is fast and supports ligatures, so it's a pitty that Victor Mono isn't compatible with it.

**Comment by rubjo** [comment]
Yeah, I'm sorry, @cloudhead, but for now, I'm keeping the extended Q and Z tails/swirls as design features (you can call them bugs if you want to) for the italic style.

I'm happy to consider restraining the glyph width if other widely used apps/browsers/font renderers use/starts adopting an approach of resizing/fitting font glyphs. 👍

**Comment by cloudhead** [comment]
Gotcha, thanks :+1:

**Comment by mehalter** [comment]
@rubjo do you think it would be possible to add a configuration variant for a "true monospace" support?

**Comment by rubjo** [comment]
I'm sorry, but time and other work dictate that's not a priority as long as 99.9% of apps can render the fonts as designed.
