### ISSUE TITLE
VSCode theme with Victor Mono in mind

### ISSUE THREAD

**Issue by tomByrer** [rubjo/victor-mono#45]
More of a FYI, but feel free to add the link to your website / README.  Also helpful if you want more screenshots.

https://marketplace.visualstudio.com/items?itemName=tomByrer.nord-city-theme

PS, hope you don't mind I borrowed your website code for a demo ;)

**Comment by rubjo** [comment]
Very, very ...eh, cool. As in beautiful theme, nice&cold colours and don't mind at all if you use the site code. 👍 

From your screenshots, I'm now definitely understanding your `i` rendering issue. Next release (a couple of weeks off) should render much better in Windows on non-HDPI displays.
