### ISSUE TITLE
powerline/terminal setup

### ISSUE THREAD

**Issue by kwmlodozeniec** [rubjo/victor-mono#49]
Not an issue, more of a question. How did you achieve the terminal look in the screenshot on your website and in the readme? When I set Victor mono as my font in iTerm2 with Oh my ZSH none of the icons work.

**Comment by rubjo** [comment]
It’s iTerm2 with [Powerline10k](https://github.com/romkatv/powerlevel10k) inside a Git repo folder, if that helps.

**Comment by ralgozino** [comment]
Hello! I'm also using iTerm2+Powerlevel10k, would you consider making a patched "nerd" variation with all the glyphs?

**Comment by rubjo** [comment]
Hi @ralgozino,

I believe it’s already done by the nerd-fonts team, head over to https://github.com/ryanoasis/nerd-fonts and have a look.

Their version might not be the latest, but as far as I remember, they have instructions on how to patch together a font with all the 1.4 million icons locally/manually. :D

**Comment by ralgozino** [comment]
Thank you @rubjo! I'll leave here the direct links for the next one:
- Victor Mono Regular patched with Nerd glyphs:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/VictorMono/Regular/complete
- All variants:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/VictorMono/

Looks like this on iTerm2:
A prompt like the one on the readme:
<img width="1127" alt="Screenshot 2019-10-28 at 10 05 12" src="https://user-images.githubusercontent.com/6362698/67666081-538bd280-f96b-11e9-9fac-02f38d504497.png">


My prompt:
<img width="1127" alt="Screenshot 2019-10-28 at 10 05 30" src="https://user-images.githubusercontent.com/6362698/67665857-d3656d00-f96a-11e9-8a0c-0e2cdf5f2403.png">

**Comment by rubjo** [comment]
Grazie mille! Looks pretty good!
