### ISSUE TITLE
Any recommendations for VS Code?

### ISSUE THREAD

**Issue by klippx** [rubjo/victor-mono#5]
I found this font via your recommendation on thread https://github.com/open-source-ideas/open-source-ideas/issues/10

I love the font, I really want to use it, but I just can't get it to work well with any dark theme in VS Code. I usually use Fira Code so this is what I can compare with, and I really prefer dark themes like most developers do.

I have tried a ton of different Color Themes, the one in the screenshot below is `markskelton.one-dark-pro-italic` which supports italics for comments and keywords.

With Victor Mono:
![Screenshot 2019-06-19 at 09 31 56](https://user-images.githubusercontent.com/2785359/59745495-39cbd780-9275-11e9-8c60-6394960add46.png)

With Fira Code:
![Screenshot 2019-06-19 at 09 31 38](https://user-images.githubusercontent.com/2785359/59745555-5b2cc380-9275-11e9-92b0-e234db18a3b2.png)

You can see how easy it is to read Fira Code, and while Victor Mono looks great it just isn't legible for some reason. It's like it is too thin for this dark background.

I am using default font smoothing (subpixel rendering), default font weight, I installed the .TTF files, I am using a Mac. I have tried different smoothing and it just makes things worse.

Sad fact is that this font is more legible on light themes 😢 
![Screenshot 2019-06-19 at 09 37 55](https://user-images.githubusercontent.com/2785359/59745909-10f81200-9276-11e9-92e4-2079512f74a0.png)

So I guess I would like you to try VS Code, see if you can get Victor Mono to work well with a Dark Theme and then share your findings and screenshots. This would help me a lot.

**Comment by rubjo** [comment]
<img src="https://user-images.githubusercontent.com/42270947/59751405-bdd78c80-9280-11e9-937b-bbbd544ac4a7.png" align="right">
Hi, and thanks for the kind words.

This issue is familiar from my sporadic attempts to try to like VS Code.

The fix is either to wait for either:
- VS Code to render fonts on Mojave more like other apps do (there's some recent activity there, so might happen pretty soon. See here, for example: https://github.com/Microsoft/vscode/issues/59887)
or
- Me to release the font with heavier weights (just loose plans for now)

😄

**Comment by klippx** [comment]
To anyone else experiencing the same issue. 

I found out that to make a decent workaround you currently have these options:
- Change theme in vs code (just need to find one that has the italics you want for keywords/comments/etc AND is to your liking)
- Tweak screen settings; mainly increasing brightness and tuning contrast. Try quick "mode" changes (Gaming, Movie, etc)

Yes I think that a _slight_ heavier font weight would be another workaround but means more work for you. I have no idea between 100-900 what would be a good choice.

Btw, it doesn't matter on Mac which file I use to install? TTF, WOFF, WOFF2, OTF or EOT?

**Comment by rubjo** [comment]
I don't think it matters.

I had a look at how much work adding some more weights entails. It shouldn't be a massive job, but will take some time. Check again in a few weeks :)

**Comment by rubjo** [comment]
Can you give the new version with multiple weights a go and post back what you think?

I typically found that VS Code needs ~ two higher levels of weight than Sublime Text (or any browser) for the font to appear roughly the same. Weird stuff.

😃

**Comment by necmettin** [comment]
This is not a problem specific to Victor Mono actually. All 'light' fonts are pretty much unreadable or unusable in dark color schemes. Sublime and VSCode use different antialiasing (VSCode calls this font aliasing) techniques by default, you might try changing them (if the new weight rubjo provided don't work for you).

**Comment by aeadedoyin** [comment]
@klippx 
I had the same issue too. 
Here's what I did and it became legible.

    "editor.fontFamily": "Victor Mono Medium", //i.e. add "Medium"
    "editor.fontLigatures": true,
    "editor.fontWeight": "700",  //To make it even bolder (Though optional)

**Comment by kurtextrem** [comment]
Maybe adding a TTF hinted version could also help (at least on Windows, for ClearType)

**Comment by rubjo** [comment]
Closing this one now, more weights are added to make VS Code rendering a little more agreeable. TTF hinting might arrive later at some point.

**Comment by klippx** [comment]
Looks great now. Reinstalled fonts using brew, using 

```
  "editor.fontFamily": "Victor Mono",
  "editor.fontLigatures": true,
  "editor.fontWeight": "600",
  "editor.fontSize": 16
```

Selecting "Victor Mono Medium" does not work at all if you have installed the font via Homebrew. At least not for me.

**Comment by akrsnr** [comment]
"editor.fontFamily": "Victor Mono",
  "editor.fontLigatures": true,
  "editor.fontWeight": "500", // italic comment calligraphy support starts from 500 as far as I explore
  "editor.fontSize": 16
