### ISSUE TITLE
angle-brackets not tall enough

### ISSUE THREAD

**Issue by goerz** [rubjo/victor-mono#50]
for what it's worth, mathematical angle brackets do not render well. E.g. in |Ψ⟩⟨Ψ|, the brackets should match the size and position of the vertical line.

**Comment by goerz** [comment]
(nice font, otherwise)

**Comment by rubjo** [comment]
Thanks!

I’ll have a look at this for the next release.

**Comment by rubjo** [comment]
Fixed this and added some more math glyphs in 1.2.8.
