### ISSUE TITLE
Triple equal ligature spacing is not consistent on Windows

### ISSUE THREAD

**Issue by piousdeer** [rubjo/victor-mono#51]
![image](https://user-images.githubusercontent.com/31318219/67652835-5ab9dd00-f979-11e9-911d-87a3ac71e111.png)
See also: tonsky/FiraCode#405

**Comment by kurtextrem** [comment]
I actually thought this was the wanted design. Ouf.

**Comment by rubjo** [comment]
Unfortunately, agreeable hinting (line alignment/pixel snapping) on Windows when using small font sizes / non-HDPI displays can require some work.

**Comment by rubjo** [comment]
Due to the amount of work needed to possibly improve this, this isn't a priority for now. See linked cases for possible workarounds.
