### ISSUE TITLE
Greek capital Theta middle bar is rendering on top of character

### ISSUE THREAD

**Issue by georgeharito** [rubjo/victor-mono#52]
The Greek capital letter 'Θ' has the middle bar rendering above the character. This is using the OTF version of the font, on macOS High Sierra (10.13.6). This is an issue that appears to be in every font variation.
![Greek character set](https://user-images.githubusercontent.com/167681/67738638-844f3300-fa63-11e9-9ca7-52a9f3be7ce8.png)

**Comment by rubjo** [comment]
Oops, that doesn’t sound good. Will look into how that happened and fix for the next release.

**Comment by rubjo** [comment]
Fixed in 1.2.8. :)
