### ISSUE TITLE
ligatures are not working

### ISSUE THREAD

**Issue by arnoubrecht** [rubjo/victor-mono#53]
Hi everyone,

I don't get the font + ligatures working on my vs code (windows). Do I have to put the files in a specific folder on my pc? I made font to Victor Mono & enabled the ligatures. 
Any suggestions?

Kind regards,
Brecht

**Comment by rubjo** [comment]
Hi Brecht!

Is the font installed, ie. can you see the font in Windows Settings -> Fonts?

In VS Code, did you set the `editor.fontFamily` to eg. `"Victor Mono, monospace"` and `editor.fontLigatures` to `true`?

**Comment by arnoubrecht** [comment]
Hi rubjo,

Thanks for the response, no I cannot see it in my Windows Settings -> Fonts. The settings in vs code I did :). I also unzipped the VictorMonoAll. Do I have to do something else to install them?

**Comment by arnoubrecht** [comment]
Hi rubjo,

Thanks I found it :)
