### ISSUE TITLE
Punctuation renders incorrectly when italicized

### ISSUE THREAD

**Issue by sethlivingston** [rubjo/victor-mono#54]
Windows 10
JetBrains Pycharm

![image](https://user-images.githubusercontent.com/574793/68035770-53087a00-fc92-11e9-83db-2abd6bcfc6bf.png)

The first line of code is
```
@register(...
```

**Comment by rubjo** [comment]
Weird. I’m on it, thanks for reporting. :)

**Comment by sethlivingston** [comment]
Thank YOU for the wonder font!

**Comment by sethlivingston** [comment]
It appears this is affecting all punctuation when italicized:

![image](https://user-images.githubusercontent.com/574793/68040495-70424600-fc9c-11e9-9a48-e5621c4664a7.png)

The code there (a Python/Django template comment) is:
```
{# NOTE: There is (inevitable) duplication between the email templates. Be sure to update all occurrences. #}
```

**Comment by rubjo** [comment]
Quick follow-up: is this an issue in all/any other of your apps?

**Comment by sethlivingston** [comment]
Glad you asked, because it looks fine in Visual Studio Code. I will file a bug with JetBrains. Feel free to close this -- thanks.

**Comment by sethlivingston** [comment]
PyCharm issue: https://youtrack.jetbrains.com/issue/PY-38860

**Comment by sethlivingston** [comment]
Updating to the latest version of PyCharm resolved the issue. Sorry for the wild goose chase.

**Comment by rubjo** [comment]
No problemo! :)
