### ISSUE TITLE
6 and 8 are very similar

### ISSUE THREAD

**Issue by oded-cloud-endure** [rubjo/victor-mono#61]
The digits 6 and 8 look very similar, especially in bold, making it difficult to tell the difference
![Screen Shot 2019-12-11 at 10 21 18 AM](https://user-images.githubusercontent.com/55196606/70603842-18ceb880-1c00-11ea-90f1-21be673e2c34.png)

**Comment by rubjo** [comment]
I agree. This will be adjusted in the next release.

**Comment by rubjo** [comment]
Should be better now.
