### ISSUE TITLE
Can't seem to utilize the "Oblique" or "Italic" variants on my PC.

### ISSUE THREAD

**Issue by ehutchllew** [rubjo/victor-mono#62]
I recently installed Victor Mono both on my Mac and PC. For my Mac it was pretty straightforward, I just used homebrew and then added VictorMono-MediumItalic in my fontFamily settings for VSCode and it worked.

My PC has been a trip though, I can get different font weight versions of Victor Mono working (like Semibold), albeit defining it differently than I did on Mac -- instead of VictorMono-Semibold I have to write out Victor Mono Semibold. The setting defaults to the second font in the list when I try to use any form of Oblique or Italic variation. I've tried writing it like "Victor Mono Semibold Italic", "Victor Mono SemiboldItalic", "VictorMono-SemiboldItalic", etc. but nothing seems to work.

Has anyone faced this issue before? How did you resolve it? Why was this so painless on the Mac but on my PC I can't seem to get it to recognize any other font type besides the default?

**Comment by ksavery** [comment]
A quick work around for getting Italics working in windows is with the following configuration:

```
editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Italics",
      "scope": [
        "comment",
        "constant",
        "entity",
        "invalid",
        "keyword",
        "markup",
        "meta",
        "punctuation",
        "source",
        "storage",
        "string",
        "support",
        "text",
        "variable"
      ],
      "settings": {
        "fontStyle": "italic"
      }
    }
  ]
},
```

Could not get Oblique working on Windows.

**Comment by rubjo** [comment]
Although you can use the font any way you like, the usual thing to do is to specify **just the main font family** in the setting `Editor: Font Family`, and then use **themes** to control what parts of the code is set in normal / italics / bold / various colours. To set **all** the text in italics is probably not what you want – it's intended as spice here and there. This works for me:

1. Install the font files (all of them, or eg. omitting the Oblique or Italic ones).
2. Set the VS Code setting `Editor: Font Family` to `Victor Mono`.
3. Set the VS Code setting `Editor: Font Weight` to the desired weight.
4. Pick a theme that utilises the mix of normal / italics / bold / various colours you prefer.
