### ISSUE TITLE
Four Ukrainian letters are bolder than other letters

### ISSUE THREAD

**Issue by vrurg** [rubjo/victor-mono#63]
The following four symbols are bolder than others: іїґє. The following screenshot demonstrates the problem:

![Screen Shot 2020-01-01 at 10 37 21 PM](https://user-images.githubusercontent.com/1586992/71650913-7f1e9680-2ce7-11ea-9487-cc020a623a50.png)

**Comment by rubjo** [comment]
They're simply not included in the font yet, so they are displayed in your system's fallback font.

I'll add them to the next release. :)

**Comment by rubjo** [comment]
Hi @vrurg, this should be added to the latest release.

**Comment by vrurg** [comment]
Downloaded and installed. Looks great!

Thank you!
