### ISSUE TITLE
Slashed zero stylistic set

### ISSUE THREAD

**Issue by rubjo** [rubjo/victor-mono#64]

**Comment by Emexus** [comment]
Oh this would be neat, though sadly some environments ( like the Windows Command Prompt ) do not support changing stylistic sets on the go :/

**Comment by alexeyten** [comment]
There’s a tool that could “freeze” stylistic set 
https://github.com/twardoch/fonttools-utils/blob/master/pyftfeatfreeze/README.md

**Comment by rubjo** [comment]
@alexeyten That’s pretty neat.

Ideally, as more alternative glyphs/sets are (possibly) introduced, it would be nice to have some kind of easy-to-use customised font download option on the web site. Something similar to what the Input font has. I don’t know if I’ll ever find the time to make a reasonably effective workflow for it, though.

**Comment by Emexus** [comment]
@rubjo Oh that'd be amazing!
Surely extra work, but that'd allow people to easily customize it to their needs without extra knowledge about stylistic sets. Also would adress my issue :P
