### ISSUE TITLE
Italics don't show up on webstorm

### ISSUE THREAD

**Issue by vyashole** [rubjo/victor-mono#65]
I installed Victor Mono on mac via Homebrew. 
Wherever I have set it to italics on webstorm, it renders as follows. 
<img width="896" alt="Screenshot 2020-01-10 at 10 59 55 AM" src="https://user-images.githubusercontent.com/26061202/72128278-47a88d80-336a-11ea-8ca2-5b6f4d0c9362.png">

FontBook shows All font styles installed correctly.

**Comment by rubjo** [comment]
Interesting. I’ll install WebStorm and have a go. In the meantime, check out issue #47.

**Comment by vyashole** [comment]
The workaround from #47 did the job. I disabled all the oblique styles in font book and that did it. Now italics show up as cursive. But this way feels hacky. Is it a bug in catalina?

Thanks for the help and thanks a ton for the awesome font.

**Comment by rubjo** [comment]
No problem, thanks for trying it out. 🙂

There are *a lot* of font rendering-related issues on [youtrack.jetbrains.com](https://youtrack.jetbrains.com/issues?q=font%20italic), among them this one: [JBR-1776](https://youtrack.jetbrains.com/issue/JBR-1776)

**Comment by vyashole** [comment]
Oh, so according to [JBR-1776](https://youtrack.jetbrains.com/issue/JBR-1776) we can conclude it is a JetBrains issue and not a Victor Mono issue. Also, the workaround from #47 does the job. 
So I think you can close this.

**Comment by vyashole** [comment]
Mentioning all the jetbrains based products here so that the community can search this issue. 
JetBrains, IntelliJ IDEA, Webstorm, Pycharm, PHPStorm, Clion, GoLand, Android Studio

**Comment by bobhenkel** [comment]
I had the same issue with CLion from Jetbrains when trying to use Victor Mono with Rust.

What I did is go to settings->editor->ColorScheme->Rust and picked keywords and unchecked Inherit values from and checked Italic and then I started seeing Victor Mono italic. I'm guessing you could do this at a common level so all things get it but for me I only was worried about Rust. Hope it helps.

![Screenshot from 2020-04-01 13-25-18](https://user-images.githubusercontent.com/22456457/78172813-4bedbf80-741c-11ea-8a0f-4e42050422ab.png)

**Comment by obenchkroune** [comment]
Hi! 
i found a great and simple solution!
i went to settings -> Editor -> Language Defaults -> Keyword from the menu
![Annotation 2020-08-28 195420](https://user-images.githubusercontent.com/30437133/91605419-58912800-e968-11ea-9a85-7d50a2c4b43e.png)
Hope it was helpful :)

**Comment by alisanie** [comment]
Open Fontbook.app in mac os 

Select all **Oblique variants** of Victor Mono

Fn+Backspace to delete them

**Comment by kenmcd** [comment]
This issue should not have been closed.
The fonts available in the v1.5.5 release here are badly broken.
They are not going to work properly in many applications.

The easiest fix is to get the versions from Google Fonts.
Those fonts have been fixed and should work properly.
https://fonts.google.com/specimen/Victor+Mono

**Comment by thep200** [comment]
> This issue should not have been closed. The fonts available in the v1.5.5 release here are badly broken. They are not going to work properly in many applications.
> 
> The easiest fix is to get the versions from Google Fonts. Those fonts have been fixed and should work properly. https://fonts.google.com/specimen/Victor+Mono

it's work for me, thanks

**Comment by rahulj51** [comment]
Removing oblique variants worked. Thanks.
