### ISSUE TITLE
Latest zip distribution doesn't reflect changes in tag release 0.3.1 

### ISSUE THREAD

**Issue by tem1029** [rubjo/victor-mono#66]
Since the latest tag release (0.3.1) the only delta is the versioning in ``package.json`` ( https://github.com/rubjo/victor-mono/commit/fa006fd5a9775e63536d03d24934d95223c4409f ) and not the zip archive distribution itself. Was this unintentional, or is there a period of time before the latest archive is made available for everyone else?

Just to confirm this I sha256 summed both the 0.3.0 and 0.3.1 and the hashes are the same for ``VictorMonoAll.zip``. Thanks for your time and work on this project.

**Comment by rubjo** [comment]
Thanks for trying it out!

Are you saying that when you download the latest release, you're not getting v1.3.1 font files? Cache issues, maybe?

To be honest, I haven't really understood how to efficiently manage / proper order of operations for syncing this repo and the npm package victormono (or not having to install all the web site's dependencies when doing `npm install victormono`). Someone recommended lerna at one point to manage this, but I haven't had the time to plow through those docs and try to understand how that works yet.

**Comment by dtzWill** [comment]
The zip from v1.3.1 seems to be correct, looking at `VictorMonoAll.zip` from that release and the release before it:

*  https://github.com/rubjo/victor-mono/raw/v1.3.1/public/VictorMonoAll.zip
*  https://github.com/rubjo/victor-mono/raw/v1.3.0/public/VictorMonoAll.zip

They hash different, and extracting each and inspecting the files within (manually the OTF's but also with `jdupes`) shows indeed they contain different font files, and pointing `otfinto -i` at them shows they even report the right version information for each.

Take a look at how you obtained the files, maybe there's a mistake or someone baked in a revision or hash somewhere? It's happened before (on this repo! hehe).

Hope this helps, if you can't seem to get the new files report back with some information so we can debug it a bit :).

**Comment by tem1029** [comment]
Woops! This was a complete misunderstanding on my part, entirely unrelated to this project. I'm currently maintaining this package on FreeBSD, and was merged a while back but *with the wrong sha256* sum (which caused a little confusion when updating to 0.3.1) as the package version listed - feel free to remove this issue as a whole - I apologize for creating this non-existent issue. 🤦

**Comment by rubjo** [comment]
No problem at all 👍🏻
