### ISSUE TITLE
Cursive Cyrillic letters look off

### ISSUE THREAD

**Issue by Nurali9999** [rubjo/victor-mono#71]
Lowercase cursive ф looks unbalanced; the circles **must** have the same height. The lowercase cursive letters ь, ы, ъ, э, ю, я and almost all uppercase cursive letters except for Ч simply look like print italic letters. Please change those glyphs to better match this example: https://en.wikipedia.org/wiki/Russian_alphabet#Table. Thank you.

**Comment by rubjo** [comment]
Hi, and thanks for the feedback.

Cyrillic italics and cursive (with variants/completely different glyphs in different languages) are fascinating. And to me a bit complicated. 🙂

It won’t happen in the next few days, but eventually I’ll have a look at how other fonts solve this and try to improve things for the next release.

Keep healthy and safe!

**Comment by Nurali9999** [comment]
Thank you!

**Comment by den32ds** [comment]
Latin cursive r looks like Cyrillic ч, do you know typefaces with Cyrillic swashes?

**Comment by rubjo** [comment]
Still here, @Nurali9999 ?

I’m almost done with a first draft of the next version, where the Cyrillic italics are more in line with the Russian cursive style you linked to.

If possible, it would be nice to post a screenshot here and get some feedback and corrections from you and any others who are actually familiar with this style :)

**Comment by Nurali9999** [comment]
Hello, rubjo! Yes, I can give you some feedback. :)

**Comment by rubjo** [comment]
First draft. I still have some adjustment/alignment work to do. Thoughts?

![glyphs](https://user-images.githubusercontent.com/42270947/84948987-cc06f580-b0ec-11ea-97ad-db5df63bc39b.png)

![compared](https://user-images.githubusercontent.com/42270947/84948999-d1644000-b0ec-11ea-98a6-cda62b8bfd41.png)

**Comment by Nurali9999** [comment]
Most of the letters look much better now! :) However, the lowercase cursive "б" has to have a longer tail; also, the circle of the uppercase print "Ф" is a bit too low.

**Comment by Nurali9999** [comment]
PS: The lowercase cursive "н" doesn't have to have the loops; most Russian speakers I know of don't write it like that.

**Comment by alexeyten** [comment]
My 5¢

I don’t think that lowercase «б» and «ф» need that small connectors. Also lowercase letters usually doesn’t have loops. 

I would check letters with [these images](https://duckduckgo.com/?q=%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82+%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80%D0%BE%D0%BF%D0%B8%D1%81%D0%BD%D0%BE%D0%B9&t=h_&iar=images&iax=images&ia=images&iaf=size%3ALarge). They are more modern than images Wikipedia

**Comment by Nurali9999** [comment]
I agree.

> My 5¢
> 
> I don’t think that lowercase «б» and «ф» need that small connectors. Also lowercase letters usually doesn’t have loops.
> 
> I would check letters with [these images](https://duckduckgo.com/?q=%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82+%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80%D0%BE%D0%BF%D0%B8%D1%81%D0%BD%D0%BE%D0%B9&t=h_&iar=images&iax=images&ia=images&iaf=size%3ALarge). They are more modern than images Wikipedia

**Comment by rubjo** [comment]
Thanks for all input, I'll revise and post a new draft whenever I find some time in the coming days.

> ... the circle of the uppercase print "Ф" is a bit too low.

Is "print" the regular or oblique style? The circe is centered vertically, I've never seen it not be. Maybe it should be slightly bigger.

**Comment by Nurali9999** [comment]
The regular style, sorry for the confusion.
