### ISSUE TITLE
Suggestion: Reduce size of dotaccent

### ISSUE THREAD

**Issue by i-am-the-slime** [rubjo/victor-mono#72]
# I spy with my little i
I suppose this is a deliberate choice, but somehow the size of the dots on the i letter draw too much attention to them (now seeing in the preview of the following Screenshot here, I'm not too sure anymore already).
I went ahead and made them a tiny bit smaller and I like the result, so I'm curious about what you think. Here are two examples:
### Original 🍨
<img width="783" alt="Bildschirmfoto 2020-03-17 um 10 23 46" src="https://user-images.githubusercontent.com/1588055/76841925-beb24480-6839-11ea-91a5-fdbe97d99df6.png">

### Smaller dotaccent 🍫
<img width="782" alt="Bildschirmfoto 2020-03-17 um 10 24 14" src="https://user-images.githubusercontent.com/1588055/76841921-bce88100-6839-11ea-8a6c-4de46c1e2678.png">

**Comment by rubjo** [comment]
Yes, punctuation is definitely deliberately oversized, but I too have occasionally thought "is it a tad too much?". At next glance, I've typically concluded "nah, it's more clear at smaller font sizes the way it is".

I might end up taking it down 5-10% or so for the next release, but don't really know when that will be, it being the end of the world and all. 🙃

**Comment by i-am-the-slime** [comment]
Cool, thanks for your input! I forgot to say that this font blew me away by the way! I love all of the decisions you made. The only thing I dislike is that I'm starting to regret having bought PragmataPro.
On topic: I usually work on high DPI screens with font sizes no lower than 14pt, so I don't usually run into issues with low font sizes.
