### ISSUE TITLE
fix ligatures to <-|, >-| and |-<

### ISSUE THREAD

**Issue by VictorAssunc** [rubjo/victor-mono#74]
These ligatures are not good: `<-|`, `>-|` and `|-<`

![image](https://user-images.githubusercontent.com/23376064/78169002-27e3ab80-7427-11ea-90f5-371ce2784d0c.png)

**Comment by rubjo** [comment]
Not only are they not good, they aren't even included. :)

I can't see any other programming font with `>-|` nor `|-<`  for some reason. I'll see if they can be added for the next release.
