### ISSUE TITLE
Add a ligature for grouping digits of numeric literals to improve readability

### ISSUE THREAD

**Issue by juarezr** [rubjo/victor-mono#75]
Number with many digits are hard to read.

This guy added a clever way to help in this situation:
- [Commas in big numbers everywhere: An OpenType adventure](https://blog.janestreet.com/commas-in-big-numbers-everywhere/)
- He created [Numderline](https://thume.ca/numderline/) with 3 styles: Grouping, underlining and bolding.

See this [issue](https://github.com/be5invis/Iosevka/issues/453) for additional discution/opinions.

**Comment by rubjo** [comment]
After reading the issue and discussion you linked to: Personally, I think meh, a ton of work for what benefit? Also, I’m doubting this should be a part of the font itself as opposed to being a feature/setting in whatever app is outputting the font.

I’ll leave the issue here for a while.

**Comment by juarezr** [comment]
You raised some good and valid points.

Some comments:
- Some programs, like query tools, have a option for formatting numerals with dots and commas, for example.
- Most text editors and IDE don't have any setting or this. So it won't happen at that level, or only will happen in one case or two.
- This issue is most related to developers and analists. So I don't expect it for a general font.
