### ISSUE TITLE
Use font-display: swap; in the dist/index.css

### ISSUE THREAD

**Issue by spences10** [rubjo/victor-mono#77]
Hello, thanks for Victor Mono I love it!

Is there any possibility that `font-display: swap` could be added to `dist/index.css` to [Ensure text remains visible during webfont load]?

Thanks

[Ensure text remains visible during webfont load]: https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools

**Comment by rubjo** [comment]
Hi! Thanks, good idea, I’ll add it later today. 🙂

**Comment by spences10** [comment]
Whew! :sweat_smile: 

I was going to ask if you'd accept a PR if you were too busy and was also looking into how to implement this myself in a Gatsby project!
