### ISSUE TITLE
Slashed Zero Request

### ISSUE THREAD

**Issue by naimqm** [rubjo/victor-mono#78]
Hi. To start, I just want to say that I absolutely LOVE your font! It is AMAZING!! I'm definitely considering donating soon. :-)

Do you happen to have plans for a slashed zero option? I'm not sure if this is a very common stylistic request, but I am curious to hear if something like this would be possible.

Thank you for the fantastic font. <3

**Comment by rubjo** [comment]
Hi @naimqm, and thanks for the kind words. 🙂

A slashed zero is actually already included as stylistic set number 01. To use it, add `"font_options": ["ss01"]` to your settings for Sublime Text or `"editor.fontLigatures": "'ss01'"` for VS Code.
