### ISSUE TITLE
Unable to install font-victor-mono from brew cask

### ISSUE THREAD

**Issue by adi3230** [rubjo/victor-mono#8]
I tried to install the font via brew cask but it throws an error saying
"Cask 'font-victor-mono' is unavailable: No Cask with this name exists."
Below is screenshot:
<img width="638" alt="error_msg_font_brew" src="https://user-images.githubusercontent.com/4820335/59968633-f1463f80-953c-11e9-883e-4fd5575895e0.png">
@rubjo Can you please point out if anything have to do prior to downloading the font?

**Comment by rubjo** [comment]
I believe you need to `brew tap homebrew/cask-fonts` first, as per instructions at https://github.com/Homebrew/homebrew-cask-fonts

**Comment by adi3230** [comment]
You are right .. It worked
Thanks @rubjo .. closing the issue
