### ISSUE TITLE
Unable to Get Glyphs to work in Gnome

### ISSUE THREAD

**Issue by typkrft** [rubjo/victor-mono#80]
Kind of an odd problem. I've been using your font for a year or so on Mac, with no issue. However I've been experimenting with Linux distros lately and I've noticed that if I use Gnome glyphs like "===" work everywhere except the terminals. I've tried gnome-terminal, alacritty, terminator, tilix, termite, guake, tilda, and maybe a couple other's, it wasn't until I installed KDE's Konsole in Gnome that I was able to get it to work again. Just curious if you had an idea why I'm using Pop!_OS if that would make any difference. Thanks for the great font also.

**Comment by rubjo** [comment]
Hi @typkrft, thanks for liking the font.

Unfortunately, this is light years above me. 😀

**Comment by alexeyten** [comment]
Gnome terminal doesn’t support ligatures

See https://github.com/tonsky/FiraCode/blob/master/README.md#terminal-compatibility-list

**Comment by rubjo** [comment]
Aha thanks @alexeyten, we’ve probably sorted that out then.

**Comment by alexeyten** [comment]
BTW, you still could use font in terminal but without ligatures.
See https://github.com/tonsky/FiraCode/issues/905#issuecomment-561129223

**Comment by typkrft** [comment]
Hey, thanks for the information. I truly appreciate the information. I'm kind of surprised gnome hasn't added ligature support in their terminals.

I'm just going to leave this here in case another noob, like myself, comes along looking for a possible solution.

If you want to use ligatures, but don't want to bork up your Gnome install with a bunch of KDE/QT dependencies for Konsole. Check out, Kitty (https://github.com/kovidgoyal/kitty).

Example Config:

```
font_family       VictorMono Nerd Font Mono
bold_font         auto
italic_font       auto
bold_italic_font  auto
```
