### ISSUE TITLE
VSCODE minimap is misbehaving in word wrap

### ISSUE THREAD

**Issue by pingala98** [rubjo/victor-mono#83]
Only when I am using the Victor Mono font, minimap of vs code is misbehaving (seems like a glitch in UI when there is need to wrap the text to next line).
Below is the link of video describing my issue:
https://youtu.be/A6Fom2hEgjI
please help me find the problem as i really love this font and my editor is becoming unusable.

vscode details:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-29-generic snap

settings.json
{
    "code-runner.runInTerminal": true,
    "debug.allowBreakpointsEverywhere": true,
    "window.menuBarVisibility": "toggle",
    "window.zoomLevel": 0,
    "extensions.autoUpdate": false,
    "breadcrumbs.enabled": true,
    "editor.renderControlCharacters": false,
    "editor.renderWhitespace": "none",
    "workbench.activityBar.visible": true,
    "explorer.confirmDelete": false,
    "diffEditor.ignoreTrimWhitespace": true,
    "files.exclude": {
        "**/.o": true
    },
    "explorer.sortOrder": "modified",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "code-runner.preserveFocus": false,
    "code-runner.saveFileBeforeRun": true,
    "editor.formatOnSave": true,
    "editor.fontSize": 16,
    "C_Cpp.clang_format_style": "LLVM",
    "workbench.colorTheme": "One Monokai",
    "C_Cpp.errorSquiggles": "Enabled",
    "terminal.integrated.minimumContrastRatio": 4.5,
    "workbench.editor.openPositioning": "last",
    "explorer.incrementalNaming": "smart",
    "C_Cpp.clang_format_fallbackStyle": "WebKit",
    "dart.allowAnalytics": false,
    "dart.previewFlutterUiGuides": true,
    "dart.flutterSdkPath": "/usr/local/flutter",
    "editor.minimap.size": "fit",
    "editor.minimap.scale": 2,
    "editor.wordWrap": "on",
    "editor.fontLigatures": true,
    "editor.fontFamily": "'F', 'monospace', monospace, 'Victor Mono'"
}

**Comment by rubjo** [comment]
Hi, and thanks for liking the font!

Unfortunately, I don't think I'll be able to help you with this – maybe it should be a VS Code issue?
