### ISSUE TITLE
Victor Mono Light displays strange characters during Android Studio debug

### ISSUE THREAD

**Issue by Metaspark** [rubjo/victor-mono#89]
![image](https://user-images.githubusercontent.com/13188042/88075729-1ad2ff80-cb71-11ea-854e-4b10255f15bf.png)

Hi, 

When debugging in Android Studio, the "Victor Mono Light" font seems to have display issues in some panels and main editor pane as shown in the above screenshot. 

The font appears fine when using "Victor Mono", as shown below

![image](https://user-images.githubusercontent.com/13188042/88076646-3be82000-cb72-11ea-97a0-39a5f43ccde3.png)

Ligatures being enabled or disabled, do not affect the issue. 

Love the font a lot. Have a great day & stay safe!

**Comment by rubjo** [comment]
Thanks for liking the font 🙂

I’m mostly offline for some time ahead - but I suspect this might be an app rather than a font issue. Maybe there are similar issues to be found wherever issues for Android Studio live.

**Comment by Metaspark** [comment]
Thanks a lot for the response, that was very helpful. I will look out for similar issues in line with your hint. 

Cheers.
