### ISSUE TITLE
Installation via homebrew does not work

### ISSUE THREAD

**Issue by ngehlert** [rubjo/victor-mono#9]
When executing `brew cask install font-victor-mono` I get the following error

`Error: Cask 'font-victor-mono' is unavailable: No Cask with this name exists.`

**Comment by rubjo** [comment]
Hi,

Thanks for trying the font! The first time you use homebrew-cask-fonts, you need to `brew tap homebrew/cask-fonts`. I'll update the instructions to say so. :)

**Comment by ngehlert** [comment]
awesome thanks
