### ISSUE TITLE
Unable to use font variations in JetBrain IDE's

### ISSUE THREAD

**Issue by jfuto** [rubjo/victor-mono#91]
I'm only able to choose the Victor Mono font in PyCharm on macOS Mojave.  All fonts are installed from the zip and I can see them in Font Book, but I'm unable to choose my preferred font, Victor Mono Medium.

**Comment by rubjo** [comment]
This is probably a JetBrain bug, I suggest file a bug with them (see similar closed issues here). In the meantime, try just removing the weights you don't use.

**Comment by kag0** [comment]
@jfuto uncheck the box labeled "Show only monospaced fonts".
