### ISSUE TITLE
Victor mono "Bold" doesn't show up in Jetbrains IDEs 2020.2

### ISSUE THREAD

**Issue by youssefhabri** [rubjo/victor-mono#93]
As the title states, the Bold variant of the font doesn't show up in Jetbrains IDE's font dropdown list:
![Screenshot_20201018_200147](https://user-images.githubusercontent.com/1578005/96377289-c72a7f00-117c-11eb-9076-fa8111ed0052.png)

It also doesn't work in VSCode if I use `"fontFamily": "Victor Mono Bold"`:
![Screenshot_20201018_200344](https://user-images.githubusercontent.com/1578005/96377333-140e5580-117d-11eb-83a1-0cb04b9c5d4c.png)

I'm using the latest version available in the website and I'm on linux (NixOS + KDE 5.18).

Victor Mono Bold shows up in the system font management tool:
![Screenshot_20201018_200241](https://user-images.githubusercontent.com/1578005/96377309-e6291100-117c-11eb-84ca-21b96105b43a.png)

**Comment by rubjo** [comment]
Hi, and thanks for using the font!

Jetbrains: I seem to remember that their products have a checkbox to use the Bold variant (the italic style isn’t explicitly listed either)?

VS Code: did you try .fontFamily: «Victor Mono» and .fontWeight: bold or 700?

**Comment by youssefhabri** [comment]
> VS Code: did you try .fontFamily: «Victor Mono» and .fontWeight: «bold» or 700?

Yep, that's what I'm currently using. I was just wondering why using the Bold variant directly doesn't work.

> Jetbrains: I seem to remember that their products have a checkbox to use the Bold variant (the italic style isn’t explicitly listed either)?

I'm not sure about a global "Bold" toggle. The only option I can find is manually setting bold in the color scheme for everything (keywords, comments ...etc)

As for italic, yes, it doesn't show up either.

**Comment by youssefhabri** [comment]
The variants don't show up in other editors either. It seems like they only show up as part of the Regular version, not as separate versions:
![Screenshot_20201018_211734](https://user-images.githubusercontent.com/1578005/96380363-82581580-1187-11eb-9679-93d6867687c6.png)
(Kate, KDE code editor)

**Comment by rubjo** [comment]
Code: if family «Victor Mono» + weight «bold» works, then I would just use that. I don’t know why family «Victor Mono Bold» doesn’t work.

Otherwise, that certain variants are treated as variants of Regular, rather than being listed on their own, is something I’ve seen here and there.

I guess the question is: are you able to get the styles you want on the final code?

**Comment by youssefhabri** [comment]
> I guess the question is: are you able to get the styles you want on the final code?

I can in the editors that allow choosing weight, otherwise, I can't.

If its something out of your control, its fine. I really like the font (thanks for making it, btw :+1:), not being able to use Bold is a minor inconvenience, but, I just can use SemiBold instead.

**Comment by youssefhabri** [comment]
I think the issue is that it only has `Victor Mono` in the name:
![Screenshot_20201018_214401](https://user-images.githubusercontent.com/1578005/96385330-18da0600-118b-11eb-935a-70ebedee56da.png)

Whereas the ones that show up have both `Victor Mono` and `Victor Mono VARIANT`

**Comment by rubjo** [comment]
Hm, interesting. I don’t really know how to remedy that (other than only installing Bold if that’s the weight you prefer, of course).

**Comment by youssefhabri** [comment]
Ok, doing that seems to work. Thanks.

I'll let you decide whether to close this issue or not. I'm happy with the solution.
