### ISSUE TITLE
Cutt off glyph

### ISSUE THREAD

**Issue by DasHammett** [rubjo/victor-mono#94]
Hi,
Let me start by thanking you for the font. It is just amazing.
I have found a glyph wich appears to be cut off on the rendering: "✖" (I believe *might* be [this one](https://www.fileformat.info/info/unicode/char/2a2f/index.htm)).

I use the font on a [suckless st](https://st.suckless.org/) terminal and it looks like this:
![image](https://user-images.githubusercontent.com/13760961/97348871-0cdafc00-188f-11eb-8dee-591fa3267d4b.png)
Another example, this is the output from an R script:
![image](https://user-images.githubusercontent.com/13760961/97349060-47449900-188f-11eb-86ae-9ab2e1607873.png)

It would seem the glyph is taking more space than just 1 character and might be the reason it looks cutt off
![image](https://user-images.githubusercontent.com/13760961/97349216-79ee9180-188f-11eb-8952-d2ff1c9a752d.png)

I tried the font on kitty terminal and the issue is the same:
![image](https://user-images.githubusercontent.com/13760961/97349385-b28e6b00-188f-11eb-9894-268175e20032.png)

Thanks a lot for having a look, and let me know if you need anything from my side.

Kind regards,

**Comment by rubjo** [comment]
Thanks for trying and liking the font!

If you happen to use the Nerd Fonts patched version of Victor Mono, make sure you are using the Mono variant to avoid clipped glyphs.

<img width="235" alt="Skjermbilde 2020-10-28 kl  07 55 29" src="https://user-images.githubusercontent.com/42270947/97402579-0c744c80-18f3-11eb-85d9-fa46d711c062.png">
<img width="235" alt="Skjermbilde 2020-10-28 kl  07 55 24" src="https://user-images.githubusercontent.com/42270947/97402584-0da57980-18f3-11eb-9168-adf9a990b88e.png">
<img width="235" alt="Skjermbilde 2020-10-28 kl  07 55 07" src="https://user-images.githubusercontent.com/42270947/97402586-0e3e1000-18f3-11eb-96a0-bfe08bf8a6fa.png">

**Comment by DasHammett** [comment]
Hi, 

Thanks for having a look. I am not using the Nerd Fonts patched version. I re-downloaded the font directly from your website and I have the same issue.

It might be an issue with terminals in general. I installed sublime-text editor to check it out and it is rendered correctly there. I also cheked GIMP and also the glyph is correct.

Do you know why in a terminal the glyph might not render correctly but in a GUI application will?

Thanks

Kind regards,

**Comment by rubjo** [comment]
No, I'm not sure about that. Screenshots above are from iTerm on macOS, which I use. It seems to handle it well, as does the stock macOS Terminal app. When testing on Ubuntu, I see that both GNOME Terminal and Guake Terminal renders the glyph wide and clipped.

**Comment by DasHammett** [comment]
Well, I am "glad" you can reproduce the issue (so it's not just me!). I guess is a fontconfig issue then? 
If you happen to find the cause and able to fix it, that would be great. In the meantime this is not a breaking issue for me and I will happily continue to use your font.

Thank you

**Comment by DasHammett** [comment]
I investigated a bit further the issue and I narrowed it down to the actual glyph.
The affected glyph (at least) is unicode U+2716

I also noticed that the glyph is rendered correctly if I echo it:
![image](https://user-images.githubusercontent.com/13760961/97740758-07292480-1ae2-11eb-9aa5-bf0744c2c78a.png)

But it renders truncated when I add color to it (which is what happens in the R output I showed before)
![image](https://user-images.githubusercontent.com/13760961/97740850-21fb9900-1ae2-11eb-927f-fe86ff155ad6.png)
As a matter of fact, if I disable color output from R, the cross glyph is rendered correctly.

So I believe the issue is not with the font itself, but either my terminal, fontconfig, freetype or Xft (way too many).

Thanks again! I will close the issue

**Comment by DasHammett** [comment]
On the other hand... Trying different fonts render the same glyph correctly.
This is with LIberation Mono:
![image](https://user-images.githubusercontent.com/13760961/97743449-f67aad80-1ae5-11eb-92a9-9aaee57bfaad.png)
Nimbus Mono L:
![image](https://user-images.githubusercontent.com/13760961/97743535-1c07b700-1ae6-11eb-8802-3294292b448c.png)

So I am not sure... :(

**Comment by rubjo** [comment]
Could you try with this?

[1.4.2.zip](https://github.com/rubjo/victor-mono/files/5474989/1.4.2.zip)

**Comment by DasHammett** [comment]
Hi, 
Thanks for sending the new font. Now the glyph is rendered correctly in colour! 
Old:
![image](https://user-images.githubusercontent.com/13760961/97883456-2d8ad200-1d25-11eb-92ec-e6b279b9f758.png)
New:
![image](https://user-images.githubusercontent.com/13760961/97883478-354a7680-1d25-11eb-998e-4cab26ba2187.png)

I see is quite smaller than before, specially compared to a regular glyph besides it.
![image](https://user-images.githubusercontent.com/13760961/97883887-b6097280-1d25-11eb-9c9b-1f993479a5d7.png)

**Comment by rubjo** [comment]
You’re right, it is probably meant to appear as big as possible. I’ll ramp it up as much as I think the mono width allows and post another attempt some time tomorrow.

**Comment by rubjo** [comment]
Released 1.4.2 with this glyph included.
