### ISSUE TITLE
Recommended font size and line spacing?

### ISSUE THREAD

**Issue by kag0** [rubjo/victor-mono#96]
What is the recommended font size and line spacing for Victor Mono? 
I'm currently using 16pt and 0.8 line spacing, and that looks OK. But it would be nice to have some recommended values documented.

**Comment by rubjo** [comment]
I don’t see a point recommending a specific size or line height.

I will often use a different size, weight and line height depending on:
- what app I use (a terminal vs a text editor)
- what display DPI I’m looking at
- what content I’m looking at (code, prose, scripts, whatever)
