### ISSUE TITLE
Is it possible to use victor-mono with vim?

### ISSUE THREAD

**Issue by JinraeKim** [rubjo/victor-mono#99]
As the title, is it possible to use victor-mono with vim, not macvim or gvim?

I tried to use it with gvim but it's little bit annoying.
So, I wonder if the use with vim is on the plan or it's fundamentally impossible.

### Note
- With gvim, unicode inputs (specifically supported by [julia-vim](https://github.com/JuliaEditorSupport/julia-vim)) are broken.
- With vim, optional cursive italic is not applied in my case.

**Comment by rubjo** [comment]
Hi,

And sorry for not replying to this sooner.

My knowledge of Vim is (and probably always will be) non-existent, I never jumped on that bandwagon. I tried, but couldn't find anything about how to set this up.

In my experience, the people who use Vim are very often the people who are vehemently opposed to using ligatures or italics in code, so it could maybe be hard to dig up anything about how this works. I am afraid you just have to search around for a possible solution.

Take care
:)

**Comment by alexeyten** [comment]
Usually vim runs inside some terminal emulator, so the real question is how to set font in you terminal. You could check docs on your terminal

**Comment by alexeyten** [comment]
Here's an example of vim in terminal with italic
![image](https://user-images.githubusercontent.com/44377/103242432-2ff55b00-4967-11eb-9f4e-af2a5e0e9463.png)

**Comment by JinraeKim** [comment]
> Here's an example of vim in terminal with italic
> ![image](https://user-images.githubusercontent.com/44377/103242432-2ff55b00-4967-11eb-9f4e-af2a5e0e9463.png)
> 

Thank you!
Is it macvim or gvim? Or just plain vim?
In my case, it seems not work for multiple font types at once with plain vim.

If you don't mind, can you share the way you set your font like the example?

**Comment by alexeyten** [comment]
This is plain vim in Elementary terminal (libvte-based) in Elementary (Ubuntu 18.04)

What terminal do you use in Ubuntu? You should be able to set terminal font in its settings.

**Comment by JinraeKim** [comment]
@alexeyten
I don't exactly know how to call my terminal but it's just a built-in terminal on Ubuntu 20.04.
Here's the screenshot of preference and applied text examples:

![Screenshot from 2020-12-29 17-46-20](https://user-images.githubusercontent.com/43136096/103271533-d5f3a480-49fd-11eb-83d6-5202143a53b0.png)
![Screenshot from 2020-12-29 17-48-02](https://user-images.githubusercontent.com/43136096/103271596-063b4300-49fe-11eb-8e34-d22445df73a8.png)

- Note: commented out texts are not cursive italic.

**Comment by alexeyten** [comment]
May be your vim colorscheme doesn't use italic?
Check if your terminal supports italic with this command:
```bash
printf '\e[1;3mHello\e[0m\n'
```

![image](https://user-images.githubusercontent.com/44377/103283116-bc942d80-49e8-11eb-971f-977eb3314ea1.png)

**Comment by JinraeKim** [comment]
@alexeyten 
Thank you.
On my plain terminal, it seems support italic like this:
![image](https://user-images.githubusercontent.com/43136096/103326167-6bd90f00-4a92-11eb-8b1c-589bbd5a28a3.png)

On my tmux, it does not:
```
➜  ~ printf '\e[1;3mHello\e[0m\n'
Hello
```

By the way, I can make all texts be italic by changing preference on terminal:
![image](https://user-images.githubusercontent.com/43136096/103326234-b5295e80-4a92-11eb-83e8-fc4ec28f492b.png)

**Comment by alexeyten** [comment]
Well, you should fix your tmux. Google for “tmux italic”. There are plenty of solutions.

**Comment by rubjo** [comment]
Thanks for helping, Alexey! 👍🏻🙂

**Comment by JinraeKim** [comment]
@alexeyten 
I really thank you :)

But I suspect that it's not a problem of tmux. Because with the plain terminal (without tmux), italic is available but victor mono's  simultaneous support of normal font and cursive italic (enabled by comment out).

Anyhow, I'm googling what you suggested :) thanks again.

**Comment by EpsilonKu** [comment]
@JinraeKim 

Your tmux need support italic and font ligature. It doesn't depend on vim.

**Comment by JinraeKim** [comment]
@EpsilonKu Actually I don't think that it's a matter of tmux cuz it's not working on plain terminals, e.g., default terminal for Ubuntu and iterm2 for macOS.
If you're using this on iterm2, can you share your preference of iterm2 or setup procedure to duplicate it?

**Comment by alexeyten** [comment]
I've lost what the problem is.
First check if you terminal and tmux supports italic
```bash
printf 'Hello, \e[1;3mitalic!\e[0m Regular again.\n'
```
should output something like this:
![Screenshot from 2021-01-27 10-28-19](https://user-images.githubusercontent.com/44377/105957516-6cad9280-608a-11eb-87fd-64f394bfb9db.png)

then check if your vim supports italic

**Comment by JinraeKim** [comment]
@alexeyten Welcome back :)
As I told you, apart from tmux, there is no italic support issue (at least) on my plain terminal.

My question is, how to use optional cursive italic "at the same time".
For example, by setting my terminal font as "Victor mono Bold", it looks like
![image](https://user-images.githubusercontent.com/43136096/105959719-a220a300-60bf-11eb-8106-77209e5ae6ea.png)
and with "Victor mono Bold Italic"
![image](https://user-images.githubusercontent.com/43136096/105959781-b1075580-60bf-11eb-9a4d-8b6bd20492bc.png).

Note: ligature is also fine.
![image](https://user-images.githubusercontent.com/43136096/105960070-122f2900-60c0-11eb-9b89-a3417fe9906a.png)

**Comment by rubjo** [comment]
Is https://apple.stackexchange.com/questions/266333/how-to-show-italic-in-vim-in-iterm2 helpful?

**Comment by alexeyten** [comment]
Earlier you wrote

> On my plain terminal, it seems support italic like this:
> ![image](https://user-images.githubusercontent.com/43136096/103326167-6bd90f00-4a92-11eb-8b1c-589bbd5a28a3.png)

What have changed?

**Note** you should set your terminal font to `Victor Mono` (not bold, not italic, just plain name).

**Comment by JinraeKim** [comment]
Before answering your questions, I really appreciate that you all keep answering my questions and being kind. Thanks a lot :)

To @alexeyten,
I may didn't understand what you said.
For clarity, I'll explain my question and status briefly.
First, I'm trying to use victor mono for optional cursive italics (especially for commented out text).
According to you, it is possible to use as I desire in plain vim:

> Here's an example of vim in terminal with italic
> ![image](https://user-images.githubusercontent.com/44377/103242432-2ff55b00-4967-11eb-9f4e-af2a5e0e9463.png)

Anyway, I tried to some fixes as people told me.
I think that my terminal has no issue for italic support as I posted:


> @alexeyten
> Thank you.
> On my plain terminal, it seems support italic like this (apart from tmux):
> ![image](https://user-images.githubusercontent.com/43136096/103326167-6bd90f00-4a92-11eb-8b1c-589bbd5a28a3.png)
> 
> On my tmux, it does not:
> 
> ```
> ➜  ~ printf '\e[1;3mHello\e[0m\n'
> Hello
> ```

and

> @alexeyten Welcome back :)
> As I told you, apart from tmux, there is no italic support issue (at least) on my plain terminal.
> 
> My question is, how to use optional cursive italic "at the same time".
> For example, by setting my terminal font as "Victor mono Bold", it looks like
> ![image](https://user-images.githubusercontent.com/43136096/105959719-a220a300-60bf-11eb-8106-77209e5ae6ea.png)
> and with "Victor mono Bold Italic"
> ![image](https://user-images.githubusercontent.com/43136096/105959781-b1075580-60bf-11eb-9a4d-8b6bd20492bc.png).
> 
> Note: ligature is also fine.
> ![image](https://user-images.githubusercontent.com/43136096/105960070-122f2900-60c0-11eb-9b89-a3417fe9906a.png)

To your question about what have changed, I think there's no big difference cuz my terminal already supported italic fonts.
By the way, I can set my terminal font using victor mono like this (now, it's iterm2 on macOS, so it may look different):
![image](https://user-images.githubusercontent.com/43136096/105968268-32fc7c00-60ca-11eb-8d1f-f7b96cf47765.png)
So, there's no choice of just 'victor mono'. It may be the reason why I cannot use it properly.


To @rubjo,
As mentioned above, I don't think that @rubjo  recommendation can be applied to this case cuz it does not seem that it's a matter of italic support of terminal or vim. Sorry.
> Is https://apple.stackexchange.com/questions/266333/how-to-show-italic-in-vim-in-iterm2 helpful?

**Comment by rubjo** [comment]
Well, I followed the instructions in the link:

![Skjermbilde 2021-01-27 kl  10 14 07](https://user-images.githubusercontent.com/42270947/105969354-72a27400-6088-11eb-95ef-61ffd135d3c8.png)

![Skjermbilde 2021-01-27 kl  10 15 33](https://user-images.githubusercontent.com/42270947/105969555-ac737a80-6088-11eb-95c2-6c4a0b023182.png)

**Comment by JinraeKim** [comment]
![image](https://user-images.githubusercontent.com/43136096/105971878-5b867500-60ce-11eb-955f-1e6fdbe426fd.png)

Finally, I get this!
HWIW... it was really tough :)

For some users struggling with this like me, I'm leaving some comments:

1) vim with optional italic is possible. As @rubjo pointed out, some setting for vimrc is required:

> Is https://apple.stackexchange.com/questions/266333/how-to-show-italic-in-vim-in-iterm2 helpful?

2) As @alexeyten pointed out, some colorscheme may not support italic (especially only for comments).
For `gruvbox`, see [this](https://github.com/morhetz/gruvbox/issues/119#issuecomment-226301453).

> May be your vim colorscheme doesn't use italic?
> Check if your terminal supports italic with this command:
> 
> ```shell
> printf '\e[1;3mHello\e[0m\n'
> ```
> 
> ![image](https://user-images.githubusercontent.com/44377/103283116-bc942d80-49e8-11eb-971f-977eb3314ea1.png)
